#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python3 server/manage.py migrate
ddtrace-run python3 server/manage.py runserver 0.0.0.0:8000
# run this once
python3 server/manage.py createsuperuser admin+support@mymanagr.com
