# Generated by Django 2.2.24 on 2021-09-03 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesloft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesloftAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('salesloft_id', models.IntegerField()),
                ('guid', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('team_id', models.IntegerField()),
                ('auth_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='salesloft.SalesloftAuthAccount')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesloft_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
