# Generated by Django 2.2.24 on 2021-09-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesloft', '0002_salesloftaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesloftaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salesloftaccount',
            name='team_id',
            field=models.IntegerField(blank=True),
        ),
    ]
