# Generated by Django 2.2.24 on 2021-09-10 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('salesloft', '0003_auto_20210908_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesloftauthaccount',
            name='token_generated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='SLAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('account_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sl_accounts', to='salesloft.SalesloftAccount')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('cadence_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_team_cadence', models.BooleanField()),
                ('is_shared', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadences', to='salesloft.SalesloftAccount')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
