# Generated by Django 2.2.24 on 2021-09-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesloft', '0004_auto_20210910_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesloftauthaccount',
            name='token_generated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
