# Generated by Django 2.2.24 on 2021-11-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesloft', '0006_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
