# Generated by Django 2.2.19 on 2021-05-10 12:33

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('group_condition', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], help_text='Applied to itself for multiple groups AND/OR group1 AND/OR group 2', max_length=255)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('alert_level', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='AlertOperand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('operand_condition', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], help_text='Applied to itself for multiple groups AND/OR group1 AND/OR group 2', max_length=255)),
                ('operand_type', models.CharField(help_text='field indicates sobject field non_field indicates managr model fields', max_length=255)),
                ('operand_identifier', models.CharField(help_text='Name of the field or managr constraint', max_length=255)),
                ('operand_operator', models.CharField(max_length=255)),
                ('operand_value', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operands', to='alerts.AlertGroup')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='AlertMessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('bindings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('notification_text', models.TextField(blank=True, help_text='This is the message that appears in the slack notification when the app is closed/out of view')),
                ('body', models.TextField(help_text='This is the message the user will see in their notification message')),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_template', to='alerts.AlertTemplate')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='AlertInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('rendered_text', models.TextField(help_text='This is the original text rendered at time of send,if for some reason an update has occured it will not show the new message but the original,use to_rendered_text for the updated message')),
                ('resource_id', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='alerts.AlertTemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='alerts.AlertTemplate'),
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('recurrence_frequency', models.CharField(default='WEEKLY', help_text='Weekly/Monthly will run on these days', max_length=255)),
                ('recurrence_day', models.SmallIntegerField(help_text='day of week/ month')),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='Currently UI will only send one recipient will change in the future', size=None)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='alerts.AlertTemplate')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
