# Generated by Django 2.2.19 on 2021-05-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertgroup",
            name="group_order",
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alertoperand",
            name="operand_order",
            field=models.SmallIntegerField(),
            preserve_default=False,
        ),
    ]
