# Generated by Django 2.2.19 on 2021-05-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20210511_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertgroup',
            options={'ordering': ['group_order']},
        ),
        migrations.AlterModelOptions(
            name='alertoperand',
            options={'ordering': ['operand_order']},
        ),
    ]
