# Generated by Django 2.2.19 on 2021-05-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20210511_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertoperand',
            name='data_type',
            field=models.CharField(help_text='To what data type we are comparing to, all data types are converted to either string, date, decimal', max_length=255, null=True),
        ),
    ]
