# Generated by Django 2.2.19 on 2021-05-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertoperand_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinstance',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
