# Generated by Django 2.2.19 on 2021-05-17 18:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20210512_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinstance',
            name='instance_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='an object holding some metadata results_count: # across alert, query_sent: copy of sql, errors: Array of any errors ', null=True),
        ),
    ]
