# Generated by Django 2.2.20 on 2021-06-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alertinstance_instance_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='recipient_type',
            field=models.CharField(default='USER_LEVEL', max_length=255),
        ),
        migrations.AddField(
            model_name='alertinstance',
            name='channel',
            field=models.CharField(help_text='Channel the alert should be sent to added 06/30/21', max_length=255, null=True),
        ),
    ]
