# Generated by Django 2.2.20 on 2021-06-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alertinstance_instance_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='recipient_type',
            field=models.CharField(default='USER_LEVEL', max_length=255),
        ),
        migrations.AddField(
            model_name='alertinstance',
            name='channel',
            field=models.CharField(help_text='Channel the alert should be sent to added 06/30/21', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='alertinstance',
            name='config',
            field=models.ForeignKey(help_text='Config was set on 06/30/21 and will only have data for that date', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='alerts.AlertConfig'),
        ),
    ]
