# Generated by Django 2.2.24 on 2021-07-13 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0007_auto_20210629_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='alert_targets',
            field=models.ManyToManyField(related_name='alert_config_targets', to=settings.AUTH_USER_MODEL),
        ),
    ]
