# Generated by Django 2.2.24 on 2021-07-14 17:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_auto_20210629_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='alert_targets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
