# Generated by Django 2.2.24 on 2021-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_alertconfig_alert_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinstance',
            name='invocation',
            field=models.PositiveIntegerField(default=0, help_text='Keeps track of the number of times this alert has been triggered, this is used to inform the workspace and paginate slack views'),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='invocation',
            field=models.PositiveIntegerField(default=0, help_text='Keeps track of the number of times this alert has been triggered, this is used to inform the workspace and paginate slack views'),
        ),
        migrations.AddField(
            model_name='alerttemplate',
            name='last_invocation_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
