# Generated by Django 2.2.24 on 2021-11-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20210726_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinstance',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
