# Generated by Django 2.2.24 on 2022-04-21 19:31

import django.contrib.postgres.fields
from django.db import migrations, models
import managr.alerts.models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alertinstance_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfig',
            name='recurrence_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=managr.alerts.models.default_days, size=None),
        ),
    ]
