# Generated by Django 2.2.24 on 2022-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alertconfig_recurrence_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertconfig',
            name='recurrence_day',
            field=models.SmallIntegerField(blank=True, help_text='day of week/ month', null=True),
        ),
    ]
