# Generated by Django 2.2.24 on 2022-05-26 20:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_auto_20220422_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttemplate',
            name='target_reference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
