# Change this to your project's node version
image: node:12.0.0

clone:
  depth: full

djangoTests: &djangoTests
  name: Django Tests
  caches:
    - pip
  image: python:3.7.3
  script:
    - pip install pipenv
    - pipenv install --system --deploy --ignore-pipfile
    - cp server/.env.example .env
    - cd server
    - IN_CI=True python manage.py test
  services:
    - postgres

e2eTests: &e2eTests
  name: E2E tests
  caches:
    - node
    - npm
    - cypress
  image: cypress/base:10
  script:
    - cd client
    - NPM_PRIVATE_TOKEN=$NPM_PRIVATE_TOKEN npm ci
    - NPM_PRIVATE_TOKEN=$NPM_PRIVATE_TOKEN npm run ci

vueAppBuild: &vueAppBuild
  name: Build Vue App
  caches:
    - node
    - npm
    - cypress
  script:
    - cd client
    - NPM_PRIVATE_TOKEN=$NPM_PRIVATE_TOKEN npm ci
    - NPM_PRIVATE_TOKEN=$NPM_PRIVATE_TOKEN npm run build
  artifacts:
    - dist/**/

herokuStagingDeployment: &herokuStagingDeployment
  name: Deploy to Heroku Staging Environment
  deployment: staging
  script:
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop:master -f

prDeployment: &prDeployment
  name: Deploy PR to AWS Fargate
  deployment: test
  script:
    - docker build -f deploy/server/Dockerfile -t $MANAGR_SERVER_IMAGE_NAME:pr-$BITBUCKET_PR_ID .

    - pipe: atlassian/aws-ecr-push-image:1.3.0
      variables:
        IMAGE_NAME: $MANAGR_SERVER_IMAGE_NAME
        TAGS: pr-$BITBUCKET_PR_ID # Optional
        # DEBUG: "<boolean>" # Optional

    - IMAGE_NAME="$MANAGR_SERVER_IMAGE_NAME:pr-$BITBUCKET_PR_ID" ./deploy/update-task.sh

    - pipe: atlassian/aws-ecs-deploy:1.5.0
      variables:
        CLUSTER_NAME: $AWS_ECS_CLUSTER_NAME
        SERVICE_NAME: $AWS_SERVICE_NAME
        TASK_DEFINITION: 'task-definition.json' # Optional
        FORCE_NEW_DEPLOYMENT: 'true' # Optional
        WAIT: 'true' # Optional 
        # DEBUG: '<string>' # Optional

fargateStagingDeployment: &fargateStagingDeployment
  name: Deploy Staging to AWS Fargate
  deployment: staging
  script:
    - docker build -f deploy/server/Dockerfile -t $MANAGR_SERVER_IMAGE_NAME:staging-$BITBUCKET_COMMIT .

    - pipe: atlassian/aws-ecr-push-image:1.3.0
      variables:
        IMAGE_NAME: $MANAGR_SERVER_IMAGE_NAME
        TAGS: staging-$BITBUCKET_COMMIT # Optional
        # DEBUG: "<boolean>" # Optional

    - IMAGE_NAME="$MANAGR_SERVER_IMAGE_NAME:staging-$BITBUCKET_COMMIT" ./deploy/update-task.sh

    - pipe: atlassian/aws-ecs-deploy:1.5.0
      variables:
        CLUSTER_NAME: $AWS_ECS_CLUSTER_NAME
        SERVICE_NAME: $AWS_SERVICE_NAME
        TASK_DEFINITION: 'task-definition.json' # Optional
        FORCE_NEW_DEPLOYMENT: 'true' # Optional
        WAIT: 'true' # Optional 
        # DEBUG: '<string>' # Optional

pipelines:
  # Insert other test or build pipelines here as appropriate.
  # NOTE: If this is not a Vue app, then disable the 'vueAppBuild' and 'e2eTests' steps in the pipelines below.
  pull-requests:
    '**':
      - parallel:
          - step: *vueAppBuild
          - step: *e2eTests
          - step: *djangoTests
      - step: *prDeployment
  branches:
    develop:
      - parallel:
          - step: *djangoTests
          - step: *e2eTests
      - parallel:
          - step: *herokuStagingDeployment
          - step: *fargateStagingDeployment

definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
  services:
    postgres:
      image: postgres
      environment:
        # Update the POSTGRES_USER variable to what is specified in your .env file.
        POSTGRES_DB: test_db
        POSTGRES_USER: managr
        POSTGRES_PASSWORD: manager
