FILE_TYPE_OTHER = 'OTHER'
FILE_TYPE_CONTRACT = 'CONTRACT'
FILE_TYPE_CHOICES = ((FILE_TYPE_OTHER, 'Other'), (FILE_TYPE_CONTRACT, 'Contract'))

LEAD_STATUS_READY = 'READY'
LEAD_STATUS_TRIAL = 'TRIAL'
LEAD_STATUS_DEMO = 'DEMO'
LEAD_STATUS_WAITING = 'WAITING'
LEAD_STATUS_CLOSED = 'CLOSED'
LEAD_STATUS_LOST = 'LOST'
LEAD_STATUS_BOOKED = 'BOOKED'
LEAD_STATUS_CHOICES = (
    (LEAD_STATUS_READY, 'Ready'),
    (LEAD_STATUS_TRIAL, 'Trial'),
    (LEAD_STATUS_DEMO, 'Demo'),
    (LEAD_STATUS_WAITING, 'Waiting'),
    (LEAD_STATUS_CLOSED, 'Closed'),
    (LEAD_STATUS_LOST, 'Lost'),
    (LEAD_STATUS_BOOKED, 'Booked'),
)

LEAD_RATING_CHOICES = [
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
]

LEAD_STATE_CLAIMED = 'CLAIMED'
LEAD_STATE_UNCLAIMED = 'UNCLAIMED'
LEAD_STATE_CHOICES = (
    (LEAD_STATE_CLAIMED, 'Claimed'),
    (LEAD_STATE_UNCLAIMED, 'Unclaimed'),
)

FORECAST_FIFTY_FIFTY = '50/50'
FORECAST_NA = 'NA'
FORCAST_STRONG = 'STRONG'
FORECAST_FUTURE = 'FUTURE'
FORECAST_VERBAL = 'VERBAL'
FORECAST_CHOICES = (
    (FORECAST_FIFTY_FIFTY, '50/50'),
    (FORECAST_NA, 'NA'),
    (FORCAST_STRONG, 'Strong'),
    (FORECAST_FUTURE, 'Future'),
    (FORECAST_VERBAL, 'Verbal'),
)

ACTIVITY_NOTE_ADDED = 'NOTE_ADDED'
ACTIVITY_NOTE_DELETED = 'NOTE_DELETED'
ACTIVITY_NOTE_UPDATED = 'NOTE_UPDATED'
ACTIVITY_LEAD_CREATED = "LEAD_CREATED"
ACTIVITY_LEAD_UPDATED = "LEAD_UPDATED"
ACTIVITY_LEAD_CLAIMED = "LEAD_CLAIMED"
ACTIVITY_LEAD_UNCLAIMED = "LEAD_UNCLAIMED"
ACTIVITY_CHOICES = (
    (ACTIVITY_NOTE_ADDED, 'Note Added'),
    (ACTIVITY_NOTE_DELETED, 'Note Deleted'),
    (ACTIVITY_NOTE_UPDATED, 'Note Updated'),
)

NOTIFICATION_ACTION_SNOOZE = 'SNOOZE'
NOTIFICATION_ACTION_VIEWED = 'VIEWED'
NOTIFICATION_ACTION_CHOICES = (
    (NOTIFICATION_ACTION_SNOOZE, 'Snooze'),
    (NOTIFICATION_ACTION_VIEWED, 'Viewed'),
)