# Generated by Django 2.2.24 on 2023-06-21 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagrToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.Token')),
                ('expiration', models.DateTimeField(default=datetime.datetime(2023, 6, 28, 19, 43, 5, 497013, tzinfo=utc))),
                ('is_revoked', models.BooleanField(default=False)),
            ],
            bases=('authtoken.token',),
        ),
    ]
