# Generated by Django 2.2.24 on 2023-06-29 15:20

from django.db import migrations, models
import managr.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managrtoken',
            name='expiration',
            field=models.DateTimeField(default=managr.api.models.set_expiration),
        ),
    ]
