# Generated by Django 2.2.24 on 2023-06-27 13:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managrtoken',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 13, 37, 55, 862517, tzinfo=utc)),
        ),
    ]
