# Generated by Django 2.2.24 on 2023-06-28 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230627_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managrtoken',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 3, 34, 34, 622642, tzinfo=utc)),
        ),
    ]
