# Generated by Django 2.2.12 on 2020-04-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organization',
        ),
    ]
