# Generated by Django 2.2.12 on 2020-04-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200406_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='rank',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
