# Generated by Django 2.2.12 on 2020-04-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_contact_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email', 'account')},
        ),
    ]
