# Generated by Django 2.2.12 on 2020-05-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200422_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
