# Generated by Django 2.2.24 on 2021-09-27 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gongaccount',
            old_name='Gong_id',
            new_name='gong_id',
        ),
        migrations.AlterField(
            model_name='gongaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gong_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gongauthaccount',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gong_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gongauthaccount',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gong_auth_account', to='organization.Organization'),
        ),
    ]
