# Generated by Django 2.2.24 on 2021-09-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gongaccount',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='gongaccount',
            name='team_id',
        ),
    ]
