# Generated by Django 2.2.24 on 2021-09-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0002_auto_20210928_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gongaccount',
            name='gong_id',
            field=models.CharField(max_length=50),
        ),
    ]
