# Generated by Django 2.2.24 on 2021-09-29 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0003_auto_20210928_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='GongCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('crm_id', models.CharField(max_length=100)),
                ('crm', models.CharField(max_length=50)),
                ('gong_id', models.CharField(max_length=30)),
                ('client_system', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=50)),
                ('auth_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='gong.GongAuthAccount')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
