# Generated by Django 2.2.24 on 2021-10-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0004_gongcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gongcall',
            name='client_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gongcall',
            name='client_system',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gongcall',
            name='crm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gongcall',
            name='crm_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gongcall',
            name='gong_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
