# Generated by Django 2.2.24 on 2021-10-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0005_auto_20211001_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gongcall',
            name='auth_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='gong.GongAuthAccount'),
        ),
    ]
