# Generated by Django 2.2.24 on 2021-10-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0008_auto_20211001_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='gongcall',
            name='scheduled_date',
            field=models.DateField(null=True),
        ),
    ]
