# Generated by Django 2.2.24 on 2022-01-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gong', '0009_gongcall_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gongcall',
            name='acc_crm_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
