# Generated by Django 2.2.17 on 2021-01-13 21:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSlackIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(help_text="permissions that the Managr Slack App has in the Organization's Slack Workspace", max_length=255)),
                ('team_name', models.CharField(help_text="name of the Organization's Slack Team", max_length=255)),
                ('team_id', models.CharField(help_text="ID of the Organization's Slack Team", max_length=255)),
                ('bot_user_id', models.CharField(help_text='ID of the Managr Bot', max_length=255)),
                ('access_token', models.CharField(help_text='Slack API access token', max_length=255)),
                ('incoming_webhook', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='data leveraged to post messages from external sources into Slack', null=True)),
                ('enterprise', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="data on the Organization's Enterprise Slack Team, if any", null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to='organization.Organization')),
            ],
            options={
                'ordering': ['organization'],
            },
        ),
        migrations.CreateModel(
            name='UserSlackIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('slack_id', models.CharField(help_text='Slack ID of the User, for this workspace', max_length=255)),
                ('channel', models.CharField(help_text='Channel ID for the DM conversation between user and Managr bot', max_length=255, null=True)),
                ('organization_slack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_slack_integrations', to='slack.OrganizationSlackIntegration')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
