# Generated by Django 2.2.17 on 2021-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationslackintegration',
            name='is_revoked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userslackintegration',
            name='is_revoked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizationslackintegration',
            name='access_token',
            field=models.CharField(blank=True, help_text='Slack API access token', max_length=255, null=True),
        ),
    ]
