# Generated by Django 2.2.18 on 2021-02-10 19:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20210209_0231'),
        ('slack', '0002_auto_20210115_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgCustomSlackForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text="The configuration object for this organization's custom Slack form.")),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_slack_form', to='organization.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
