# Generated by Django 2.2.18 on 2021-02-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_remove_contact_title'),
        ('slack', '0003_orgcustomslackform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgcustomslackform',
            options={'ordering': ['resource']},
        ),
        migrations.AddField(
            model_name='orgcustomslackform',
            name='form_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('MEETING_REVIEW', 'Meeting Review')], default='CREATE', help_text='Type of forms created, can only have one of each type', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account')], default='Opportunity', help_text='Resources we currently support custom forms for', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_slack_forms', to='organization.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='orgcustomslackform',
            unique_together={('resource', 'form_type', 'organization')},
        ),
    ]
