# Generated by Django 2.2.18 on 2021-02-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20210211_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
