# Generated by Django 2.2.18 on 2021-02-24 19:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_remove_contact_title'),
        ('slack', '0005_auto_20210219_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackform',
            name='stage',
            field=models.CharField(blank=True, help_text='if this is a special stage form the stage will appear here', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orgcustomslackform',
            unique_together={('resource', 'form_type', 'organization', 'stage')},
        ),
        migrations.CreateModel(
            name='OrgCustomSlackFormInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text="The form data as a field object with a value inserted for this organization's custom Slack form.")),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='slack.OrgCustomSlackForm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_slack_form_instances', to='organization.Organization')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
