# Generated by Django 2.2.18 on 2021-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0006_auto_20210224_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='form_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('STAGE_GATING', 'Stage Gating'), ('MEETING_REVIEW', 'Meeting Review')], help_text='Type of forms created, can only have one of each type', max_length=255),
        ),
    ]
