# Generated by Django 2.2.18 on 2021-02-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0007_auto_20210224_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgcustomslackform',
            options={'ordering': ['resource', '-stage']},
        ),
    ]
