# Generated by Django 2.2.19 on 2021-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0011_auto_20210301_1933'),
        ('slack', '0008_auto_20210225_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackform',
            name='fields',
            field=models.ManyToManyField(related_name='form_fields', to='salesforce.SObjectField'),
        ),
    ]
