# Generated by Django 2.2.19 on 2021-03-10 01:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0009_auto_20210309_1853"),
        ("slack", "0008_auto_20210225_1602"),
    ]

    operations = [
        migrations.RemoveField(model_name="orgcustomslackforminstance", name="form_data",),
        migrations.AddField(
            model_name="orgcustomslackforminstance",
            name="resource_id",
            field=models.CharField(
                blank=True, help_text="The resource for this form (if not create", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="orgcustomslackforminstance",
            name="saved_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                help_text="The Generated form with instances of its fields as a json object",
            ),
        ),
        migrations.AddField(
            model_name="orgcustomslackforminstance",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="salesforce.MeetingWorkflow",
            ),
        ),
        migrations.AlterField(
            model_name="orgcustomslackform",
            name="resource",
            field=models.CharField(
                choices=[
                    ("Opportunity", "Opportunity"),
                    ("Account", "Account"),
                    ("Contact", "Contact"),
                    ("Lead", "Lead"),
                ],
                help_text="Resources we currently support custom forms for",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="orgcustomslackforminstance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_slack_form_instances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="salesforce.SObjectField",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slack.OrgCustomSlackForm"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="orgcustomslackform",
            name="fields",
            field=models.ManyToManyField(through="slack.FormField", to="salesforce.SObjectField"),
        ),
    ]
