# Generated by Django 2.2.19 on 2021-03-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_auto_20210310_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgcustomslackform',
            options={'ordering': ['resource']},
        ),
    ]
