# Generated by Django 2.2.19 on 2021-03-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0009_orgcustomslackform_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Lead', 'Contact')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
