# Generated by Django 2.2.19 on 2021-03-03 00:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0016_meetingworkflow'),
        ('slack', '0010_auto_20210302_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgcustomslackforminstance',
            name='form_data',
        ),
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='resource_id',
            field=models.CharField(blank=True, help_text='The resource for this form (if not create', max_length=255),
        ),
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='review_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='salesforce.MeetingWorkflow'),
        ),
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='saved_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The Generated form with instances of its fields as a json object'),
        ),
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Lead', 'Contact'), ('Lead', 'Lead')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
