# Generated by Django 2.2.19 on 2021-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0010_auto_20210310_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslackintegration',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text="When a user opens the home tab it will notifiy us (or messages tab) slack requires an 'onboarding' interaction to be sent, since this event is recurring we only do it once"),
        ),
    ]
