# Generated by Django 2.2.19 on 2021-04-26 18:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0010_auto_20210310_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackform',
            name='stage_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Stage Forms will be ordered based on the order defined here', null=True, size=None),
        ),
    ]
