# Generated by Django 2.2.19 on 2021-03-03 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0011_auto_20210303_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackforminstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_slack_form_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
