# Generated by Django 2.2.19 on 2021-06-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slack", "0011_userslackintegration_is_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="include_in_recap",
            field=models.BooleanField(default=True),
        ),
    ]
