# Generated by Django 2.2.20 on 2021-06-24 19:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0012_formfield_include_in_recap'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='is_submitted',
            field=models.BooleanField(default=False, help_text='If sf returned a success this will be true, this was set up on 06/25/2021 and will only be valid for forms therafter'),
        ),
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='previous_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='This will hold previous data for updated forms'),
        ),
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='submission_date',
            field=models.DateTimeField(help_text='Date form was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='orgcustomslackforminstance',
            name='saved_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='The data submitted on the form'),
        ),
    ]
