# Generated by Django 2.2.19 on 2021-03-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0012_auto_20210303_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackforminstance',
            name='review_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='salesforce.MeetingWorkflow'),
        ),
    ]
