# Generated by Django 2.2.23 on 2021-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0012_formfield_include_in_recap'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizationslackintegration',
            constraint=models.UniqueConstraint(fields=('team_id',), name='unique_team_id'),
        ),
    ]
