# Generated by Django 2.2.19 on 2021-06-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0012_formfield_include_in_recap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='include_in_recap',
            field=models.BooleanField(default=True),
        ),
    ]
