# Generated by Django 2.2.20 on 2021-06-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0013_auto_20210623_1859'),
        ('slack', '0013_auto_20210624_1940'),
    ]

    operations = [
    ]
