# Generated by Django 2.2.19 on 2021-03-04 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0013_auto_20210304_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgcustomslackforminstance',
            old_name='review_workflow',
            new_name='workflow',
        ),
    ]
