# Generated by Django 2.2.24 on 2021-08-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0014_merge_20210630_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='update_source',
            field=models.CharField(blank=True, help_text='On update forms, sets the source of the update', max_length=30),
        ),
    ]
