# Generated by Django 2.2.24 on 2021-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0015_orgcustomslackforminstance_update_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslackintegration',
            name='zoom_channel',
            field=models.CharField(default=models.CharField(help_text='Channel ID for the DM conversation between user and Managr bot', max_length=255, null=True), help_text='Channel for zoom automation, defaults to channel', max_length=255, null=True),
        ),
    ]
