# Generated by Django 2.2.24 on 2021-11-01 16:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0016_userslackintegration_zoom_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslackintegration',
            name='recap_channel',
            field=models.CharField(help_text='Channel for recaps to be sent', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userslackintegration',
            name='recap_receivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
