# Generated by Django 2.2.19 on 2021-11-08 23:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0017_auto_20211101_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslackintegration',
            name='recap_receivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
