# Generated by Django 2.2.19 on 2021-11-11 14:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0018_auto_20211108_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslackintegration',
            name='recap_receivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
