# Generated by Django 2.2.24 on 2021-11-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0019_auto_20211111_1445'),
        ('slack', '0019_auto_20211112_1530'),
    ]

    operations = [
    ]
