# Generated by Django 2.2.24 on 2021-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0020_merge_20211112_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('Products', 'Products')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
