# Generated by Django 2.2.24 on 2021-12-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_alertinstance_completed'),
        ('slack', '0020_merge_20211112_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='alert_instance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_instance', to='alerts.AlertInstance'),
        ),
    ]
