# Generated by Django 2.2.19 on 2021-12-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0021_auto_20211209_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('Products', 'Products'), ('OpportunityLineItem', 'OpportunityLineItem')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
