# Generated by Django 2.2.19 on 2021-12-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0023_auto_20211211_0006'),
        ('slack', '0021_auto_20211211_0110'),
    ]

    operations = [
    ]
