# Generated by Django 2.2.19 on 2021-12-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0024_merge_20211211_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('Product2', 'Product2'), ('OpportunityLineItem', 'OpportunityLineItem')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
