# Generated by Django 2.2.24 on 2021-12-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0021_orgcustomslackforminstance_alert_instance_id'),
        ('slack', '0025_auto_20211212_2213'),
    ]

    operations = [
    ]
