# Generated by Django 2.2.24 on 2021-12-17 16:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0026_merge_20211213_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="The configuration object for this organization's custom Slack form."),
        ),
    ]
