# Generated by Django 2.2.24 on 2022-01-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0027_auto_20211217_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackforminstance',
            name='update_source',
            field=models.CharField(blank=True, help_text='On update forms, sets the source of the update', max_length=30, null=True),
        ),
    ]
