# Generated by Django 2.2.24 on 2022-01-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0028_auto_20220110_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslackintegration',
            name='recap_channel',
            field=models.CharField(blank=True, help_text='Channel for recaps to be sent', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userslackintegration',
            name='zoom_channel',
            field=models.CharField(blank=True, help_text='Channel for zoom automation, defaults to channel', max_length=255, null=True),
        ),
    ]
