# Generated by Django 2.2.24 on 2022-01-28 14:24

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0029_auto_20220117_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslackintegration',
            name='realtime_alert_configs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Object for all real time alert settings'),
        ),
        migrations.AlterField(
            model_name='userslackintegration',
            name='recap_receivers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text="Manager's slack id's who want a recap from this user", size=None),
        ),
    ]
