# Generated by Django 2.2.19 on 2022-02-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0030_auto_20220128_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='form_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('STAGE_GATING', 'Stage Gating')], help_text='Type of forms created, can only have one of each type', max_length=255),
        ),
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('OpportunityLineItem', 'OpportunityLineItem')], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
