# Generated by Django 2.2.24 on 2022-04-21 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0031_auto_20220215_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_id_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'Salesforce'), ('HUBSPOT', 'Hubspot')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='salesforce.SObjectField'),
        ),
    ]
