# Generated by Django 2.2.24 on 2022-09-19 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0031_auto_20220215_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='salesforce.SObjectField'),
        ),
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Salesforce', (('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('OpportunityLineItem', 'OpportunityLineItem'))), ('Hubspot', (('Deal', 'Deal'), ('Company', 'Company'), ('HubspotContact', 'HubspotContact')))], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
