# Generated by Django 2.2.24 on 2022-09-22 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_objectfield'),
        ('slack', '0032_auto_20220919_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('include_in_recap', models.BooleanField(default=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='crm.ObjectField')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slack.OrgCustomSlackForm')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
