# Generated by Django 2.2.24 on 2022-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0032_auto_20220421_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Salesforce', (('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('OpportunityLineItem', 'OpportunityLineItem'))), ('Hubspot', (('Deal', 'Deal'), ('Company', 'Company'), ('HubspotContact', 'HubspotContact')))], help_text='Resources we currently support custom forms for', max_length=255),
        ),
    ]
