# Generated by Django 2.2.24 on 2022-08-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_team'),
        ('slack', '0032_orgcustomslackform_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orgcustomslackform',
            unique_together={('resource', 'form_type', 'team', 'stage')},
        ),
    ]
