# Generated by Django 2.2.24 on 2022-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0033_auto_20220826_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackform',
            name='custom_object',
            field=models.CharField(blank=True, help_text='if this has a custom object attached this will show', max_length=255, null=True),
        ),
    ]
