# Generated by Django 2.2.24 on 2022-10-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0033_customformfield'),
        ('slack', '0033_auto_20220826_1449'),
    ]

    operations = [
    ]
