# Generated by Django 2.2.24 on 2022-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_objectfield_length'),
        ('slack', '0034_merge_20221020_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackform',
            name='custom_fields',
            field=models.ManyToManyField(through='slack.CustomFormField', to='crm.ObjectField'),
        ),
    ]
