# Generated by Django 2.2.24 on 2022-11-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0036_auto_20221027_1823'),
        ('slack', '0034_orgcustomslackform_custom_object'),
    ]

    operations = [
    ]
