# Generated by Django 2.2.24 on 2022-12-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_merge_20221020_1840'),
        ('slack', '0037_merge_20221118_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackform',
            name='resource',
            field=models.CharField(choices=[('Salesforce', (('Opportunity', 'Opportunity'), ('Account', 'Account'), ('Contact', 'Contact'), ('Lead', 'Lead'), ('OpportunityLineItem', 'OpportunityLineItem'), ('CustomObject', 'CustomObject'))), ('Hubspot', (('Deal', 'Deal'), ('Company', 'Company'), ('Contact', 'Contact'), ('CustomObject', 'CustomObject')))], help_text='Resources we currently support custom forms for', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='orgcustomslackform',
            unique_together={('resource', 'form_type', 'team', 'stage', 'custom_object')},
        ),
    ]
