# Generated by Django 2.2.24 on 2023-02-07 15:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import managr.slack.models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0038_auto_20221222_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='recap_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=managr.slack.models.DEFAULT_RECAP_DICT, null=True),
        ),
    ]
