# Generated by Django 2.2.24 on 2023-03-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0039_orgcustomslackforminstance_recap_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgcustomslackforminstance',
            name='chat_submission',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
    ]
