# Generated by Django 2.2.24 on 2023-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0040_orgcustomslackforminstance_chat_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcustomslackforminstance',
            name='chat_submission',
            field=models.TextField(blank=True, null=True),
        ),
    ]
