# Generated by Django 2.2.28 on 2024-08-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0041_auto_20230406_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslackintegration',
            name='access_token',
            field=models.CharField(blank=True, help_text='Slack API user access token', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userslackintegration',
            name='scope',
            field=models.CharField(blank=True, help_text="permissions that the user has in the Organization's Slack Workspace", max_length=255, null=True),
        ),
    ]
