# Generated by Django 2.2.24 on 2022-03-22 21:45

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import managr.hubspot.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_auto_20220119_1752'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubspot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('external_owner', models.CharField(blank=True, max_length=255)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_company', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='organization.Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='HSSyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(blank=True, max_length=255)),
                ('operations_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='An Array of operations to perform on', size=None)),
                ('operations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='An Array of task ids', size=None)),
                ('completed_operations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text="An Array of completed task id's", size=None)),
                ('failed_operations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='List of failed tasks as that failed from task runner for uncaught exceptions after 5 tries', size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hs_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubspotauthaccount',
            name='hobjects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=managr.hubspot.models.getHobjectDefaults, help_text='All resources we are retrieving', max_length=500),
        ),
        migrations.CreateModel(
            name='HSObjectFieldsOperation',
            fields=[
                ('hssyncoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hubspot.HSSyncOperation')),
            ],
            options={
                'abstract': False,
            },
            bases=('hubspot.hssyncoperation',),
        ),
        migrations.CreateModel(
            name='HubspotContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('external_owner', models.CharField(blank=True, max_length=255)),
                ('external_company', models.CharField(blank=True, max_length=255)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='hubspot.Company')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_hubspotcontact', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='HObjectField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('hubspot_object', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('calculated', models.BooleanField(default=False)),
                ('external_options', models.BooleanField(default=False)),
                ('has_unique_value', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('display_value', models.TextField(blank=True)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=255, null=True), blank=True, default=list, size=None)),
                ('display_order', models.IntegerField(default=0)),
                ('hubspot_defined', models.BooleanField(default=False)),
                ('modification_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('form_field', models.BooleanField(default=False)),
                ('hubspot_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hubspot_fields', to='hubspot.HubspotAuthAccount')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_hobjectfield', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True)),
                ('forecast_category', models.CharField(max_length=255, null=True)),
                ('close_date', models.DateField(null=True)),
                ('external_company', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('external_owner', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('stage', models.CharField(max_length=255, null=True)),
                ('last_activity_date', models.DateTimeField(null=True)),
                ('last_stage_update', models.DateTimeField(null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('reference_data', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='An array of objects containing the API Name references and values for displaying', size=None)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='hubspot.Company')),
                ('contacts', models.ManyToManyField(blank=True, related_name='contacts', to='hubspot.HubspotContact')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_deal', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
