# Generated by Django 2.2.24 on 2022-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0002_auto_20220322_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hobjectfield',
            name='display_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hobjectfield',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='hubspotcontact',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
    ]
