# Generated by Django 2.2.24 on 2022-03-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0003_auto_20220323_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobjectfield',
            name='hubspot_defined',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
