# Generated by Django 2.2.24 on 2022-03-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0004_auto_20220323_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSResourceSync',
            fields=[
                ('hssyncoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hubspot.HSSyncOperation')),
            ],
            options={
                'abstract': False,
            },
            bases=('hubspot.hssyncoperation',),
        ),
    ]
