# Generated by Django 2.2.24 on 2022-04-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0005_hsresourcesync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='last_activity_date',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='last_stage_update',
        ),
    ]
