# Generated by Django 2.2.24 on 2022-04-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0006_auto_20220408_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobjectfield',
            name='is_public',
            field=models.BooleanField(default=False, help_text="Indicates whether or not this is a managr_created field that is not part of the user's object fields"),
        ),
    ]
