# Generated by Django 2.2.24 on 2022-12-13 16:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0007_hobjectfield_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hssyncoperation',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AddField(
            model_name='hubspotauthaccount',
            name='extra_pipeline_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
