# Generated by Django 2.2.24 on 2023-02-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0008_auto_20221213_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotauthaccount',
            name='hubspot_app_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
