# Generated by Django 2.2.24 on 2023-06-28 03:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot', '0009_hubspotauthaccount_hubspot_app_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspotauthaccount',
            name='extra_pipeline_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
