# Generated by Django 2.2.17 on 2020-11-17 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('zoom_id', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255)),
                ('type', models.PositiveSmallIntegerField()),
                ('role_name', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_meeting_url', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('verified', models.PositiveSmallIntegerField()),
                ('dept', models.CharField(blank=True, max_length=255, null=True)),
                ('pic_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pmi', models.CharField(blank=True, help_text='personal meeting id', max_length=255, null=True)),
                ('use_pmi', models.BooleanField(default=False)),
                ('host_key', models.CharField(max_length=255)),
                ('jid', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_country', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=150)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_generated_date', models.DateTimeField()),
                ('token_scope', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
