# Generated by Django 2.2.17 on 2020-12-03 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0043_auto_20201023_1411'),
        ('organization', '0013_auto_20201119_1902'),
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetinReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_close_date', models.DateTimeField(blank=True, null=True)),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('sentiment', models.CharField(choices=[('GREAT', 'Great'), ('NOT WELL', 'Not Well'), ('N/A', 'N/A')], default='N/A', max_length=255)),
                ('forecast_strength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_reviews', to='lead.Forecast')),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reviews', to='zoom.ZoomMeeting')),
                ('meeting_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_reviews', to='lead.ActionChoice')),
                ('update_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_reviews', to='organization.Stage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
