# Generated by Django 2.2.17 on 2021-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomauthaccount',
            name='is_revoked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zoomauthaccount',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zoomauthaccount',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
    ]
