# Generated by Django 2.2.17 on 2020-12-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20201211_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreview',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='This field is editable', max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='prev_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='This field is editable', max_digits=13, null=True),
        ),
    ]
