# Generated by Django 2.2.17 on 2021-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20210115_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomauthaccount',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
