# Generated by Django 2.2.17 on 2020-12-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20201119_1902'),
        ('lead', '0043_auto_20201023_1411'),
        ('zoom', '0002_meetinreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetinReview',
            new_name='MeetingReview',
        ),
    ]
