# Generated by Django 2.2.17 on 2021-01-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20210119_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomauthaccount',
            name='refresh_token_task',
            field=models.CharField(blank=True, help_text='Automatically Send a Refresh task to be executed 15 mins before expiry to reduce errors', max_length=55),
        ),
    ]
