# Generated by Django 2.2.17 on 2020-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20201213_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
