# Generated by Django 2.2.17 on 2020-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20201209_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='current_interaction',
            field=models.PositiveSmallIntegerField(default=1, help_text='current slack form'),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='interaction_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PARTIAL', 'Partial'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=255),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='is closed is true when we expire attempts or a user has completed all steps'),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='latest_attempt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='notification_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='We make an attempt immedietly and after 2 hours'),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='scoring_in_progress',
            field=models.BooleanField(default=False, help_text='if an event is emitted to generate a score dont do it again'),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='forecast_strength',
            field=models.CharField(blank=True, choices=[('50/50', '50/50'), ('NA', 'NA'), ('STRONG', 'Strong'), ('FUTURE', 'Future'), ('VERBAL', 'Verbal'), ('CLOSED', 'Closed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='meeting_type',
            field=models.CharField(blank=True, help_text='The value must corespond to the values in the ActionChoice Model', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='next_steps',
            field=models.TextField(blank=True, help_text='populates secondary description', null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('GREAT', 'Great'), ('NOT WELL', 'Not Well'), ('N/A', 'N/A')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='update_stage',
            field=models.CharField(blank=True, help_text='The values must correspond to the values in the Stage model and by Org', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='updated_close_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
    ]
