# Generated by Django 2.2.17 on 2020-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_zoommeeting_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoommeeting',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('ZOOM_MEETING__GREAT', 'Great'), ('ZOOM_MEETING__NOT_WELL', 'Not Well'), ('ZOOM_MEETING__CANT_TELL', "Can't Tell")], max_length=255, null=True),
        ),
    ]
