# Generated by Django 2.2.17 on 2020-12-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_auto_20201210_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='participants_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='total_minutes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='operator',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
