# Generated by Django 2.2.17 on 2021-01-26 20:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_zoomauthaccount_refresh_token_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='Json object of participants', null=True, size=None),
        ),
    ]
