# Generated by Django 2.2.17 on 2020-12-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0005_auto_20201216_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='original_duration',
            field=models.SmallIntegerField(blank=True, help_text='Original duration is the duration sent from the meeting.end webhook, it is updated to the real duration when retrieving from the meetin endpoint so we save it for scoring', null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='prev_expected_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='updated_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
