# Generated by Django 2.2.17 on 2021-01-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0005_auto_20210126_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreview',
            old_name='prev_expected_close_date',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='meetingreview',
            old_name='forecast_strength',
            new_name='forecast_category',
        ),
        migrations.RenameField(
            model_name='meetingreview',
            old_name='next_steps',
            new_name='next_step',
        ),
        migrations.RenameField(
            model_name='meetingreview',
            old_name='updated_close_date',
            new_name='prev_close_date',
        ),
        migrations.RenameField(
            model_name='meetingreview',
            old_name='update_stage',
            new_name='stage',
        ),
    ]
