# Generated by Django 2.2.17 on 2020-12-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0005_auto_20201210_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeeting',
            name='join_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='start_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
