# Generated by Django 2.2.17 on 2020-12-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0006_auto_20201210_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeeting',
            name='status',
            field=models.CharField(blank=True, choices=[('ENDED', 'Ended'), ('STARTED', 'Started'), ('WAITING', 'Waiting'), ('CREATED', 'Created'), ('DELETED', 'Deleted')], help_text='Status of the meeting, only takes 2 values and is supplied by retrieve from zoom', max_length=255, null=True),
        ),
    ]
