# Generated by Django 2.2.17 on 2021-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0006_auto_20210126_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('OMITTED', 'Omitted'), ('PIPELINE', 'Pipeline'), ('BESTCASE', 'Best Case'), ('FORECAST', 'Commit'), ('CLOSED', 'Closed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='prev_forecast',
            field=models.CharField(blank=True, choices=[('OMITTED', 'Omitted'), ('PIPELINE', 'Pipeline'), ('BESTCASE', 'Best Case'), ('FORECAST', 'Commit'), ('CLOSED', 'Closed')], max_length=255, null=True),
        ),
    ]
