# Generated by Django 2.2.17 on 2020-12-10 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0007_auto_20201210_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_review', to='zoom.ZoomMeeting'),
        ),
    ]
