# Generated by Django 2.2.17 on 2021-01-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0007_auto_20210129_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('Omitted', 'Omitted'), ('Pipeline', 'Pipeline'), ('BestCase', 'Best Case'), ('Forecast', 'Commit'), ('Closed', 'Closed')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='prev_forecast',
            field=models.CharField(blank=True, choices=[('Omitted', 'Omitted'), ('Pipeline', 'Pipeline'), ('BestCase', 'Best Case'), ('Forecast', 'Commit'), ('Closed', 'Closed')], max_length=255, null=True),
        ),
    ]
