# Generated by Django 2.2.17 on 2021-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0008_auto_20210129_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='slack_form',
            field=models.CharField(blank=True, help_text='Id of slack form, we will use this id to delete/update the form when the meeting is deleted', max_length=255),
        ),
    ]
