# Generated by Django 2.2.17 on 2020-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0008_auto_20201210_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingreview',
            name='prev_expected_close_date',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='prev_forecast',
            field=models.CharField(blank=True, choices=[('50/50', '50/50'), ('NA', 'NA'), ('STRONG', 'Strong'), ('FUTURE', 'Future'), ('VERBAL', 'Verbal'), ('CLOSED', 'Closed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='prev_stage',
            field=models.CharField(blank=True, help_text='The values must correspond to the values in the Stage model and by Org', max_length=255, null=True),
        ),
    ]
