# Generated by Django 2.2.18 on 2021-02-08 17:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0009_zoommeeting_slack_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreview',
            name='next_step',
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='custom_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary data that is added to a form is saved as a json object for update', max_length=500, null=True),
        ),
    ]
