# Generated by Django 2.2.18 on 2021-02-16 18:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0010_auto_20210208_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreview',
            old_name='description',
            new_name='meeting_notes',
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='custom_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All data that is added to a form is saved as a json object for update', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='forecast_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='stage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
