# Generated by Django 2.2.18 on 2021-02-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_remove_contact_title'),
        ('zoom', '0011_auto_20210216_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='current_interaction',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='notification_attempts',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='should_track',
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='linked_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='organization.Account'),
        ),
    ]
