# Generated by Django 2.2.18 on 2021-02-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0012_auto_20210216_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='prev_close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
