# Generated by Django 2.2.18 on 2021-02-19 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0013_auto_20210218_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreview',
            old_name='meeting_notes',
            new_name='meeting_comments',
        ),
    ]
