# Generated by Django 2.2.18 on 2021-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0014_auto_20210219_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='slack_interaction',
            field=models.CharField(blank=True, help_text='Id of current slack message interaction, we will use this id to delete/update the interaction with its status', max_length=255),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='slack_form',
            field=models.CharField(blank=True, help_text='Id of slack form, we will use this id to delete/update the form when using an async flow', max_length=255),
        ),
    ]
