# Generated by Django 2.2.18 on 2021-02-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0015_auto_20210222_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='resource_id',
            field=models.CharField(blank=True, help_text='The id of the related resource unopinionated', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='resource_type',
            field=models.CharField(blank=True, help_text='The class name of the resource', max_length=255, null=True),
        ),
    ]
