# Generated by Django 2.2.19 on 2021-03-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0016_auto_20210224_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeeting',
            name='interaction_status',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='linked_account',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='scoring_in_progress',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='slack_form',
        ),
        migrations.RemoveField(
            model_name='zoommeeting',
            name='slack_interaction',
        ),
    ]
