# Generated by Django 2.2.19 on 2021-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0017_auto_20210309_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('ZOOM_MEETING__GREAT', 'Great'), ('ZOOM_MEETING__FINE', 'Fine'), ('ZOOM_MEETING__CANT_TELL', "Can't Tell")], max_length=255, null=True),
        ),
    ]
