# Generated by Django 2.2.19 on 2021-03-24 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0018_auto_20210309_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreview',
            name='custom_data',
        ),
        migrations.RemoveField(
            model_name='meetingreview',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='next_step',
            field=models.TextField(blank=True, help_text='If user uses next step field this will be saved'),
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='resource_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meetingreview',
            name='resource_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This field is editable', max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='prev_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This field is editable', max_digits=13, null=True),
        ),
        migrations.CreateModel(
            name='ZoomMeetingReview',
            fields=[
                ('meetingreview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zoom.MeetingReview')),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meeting_review', to='zoom.ZoomMeeting')),
            ],
            options={
                'abstract': False,
            },
            bases=('zoom.meetingreview',),
        ),
    ]
