# Generated by Django 2.2.19 on 2021-03-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0019_auto_20210324_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingreview',
            old_name='sentiment',
            new_name='meeting_sentiment',
        ),
    ]
