# Generated by Django 2.2.19 on 2021-04-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0020_auto_20210324_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingreview',
            name='meeting_sentiment',
            field=models.CharField(blank=True, choices=[('ZOOM_MEETING__GREAT', 'Great'), ('ZOOM_MEETING__FINE', 'Fine'), ('ZOOM_MEETING__NOT_WELL', 'Not Well')], max_length=255, null=True),
        ),
    ]
