# Generated by Django 2.2.19 on 2021-05-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0021_auto_20210412_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='jid',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='personal_meeting_url',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='phone_country',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='pic_url',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='pmi',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='use_pmi',
        ),
        migrations.RemoveField(
            model_name='zoomauthaccount',
            name='verified',
        ),
    ]
