# Generated by Django 2.2.19 on 2021-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0022_auto_20210513_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingreview',
            name='meeting_sentiment',
        ),
        migrations.AlterField(
            model_name='meetingreview',
            name='next_step',
            field=models.TextField(blank=True, help_text='If user uses next step field this will be saved', null=True),
        ),
    ]
