# Generated by Django 2.2.20 on 2021-06-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0023_auto_20210528_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeetingreview',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='zoommeetingreview',
            name='meetingreview_ptr',
        ),
        migrations.DeleteModel(
            name='MeetingReview',
        ),
        migrations.DeleteModel(
            name='ZoomMeetingReview',
        ),
    ]
