# Generated by Django 2.2.23 on 2021-06-30 13:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0023_auto_20210528_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoommeetingreview',
            name='meetingreview_ptr',
        ),
        migrations.AddField(
            model_name='zoommeetingreview',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoommeetingreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='zoommeetingreview',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='MeetingReview',
        ),
    ]
