# Generated by Django 2.2.24 on 2021-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0024_auto_20210630_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomauthaccount',
            name='host_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
