# Generated by Django 2.2.24 on 2022-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0025_auto_20211210_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoomauthaccount',
            name='fake_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
