MEETING_STATUS_WAITING = "WAITING"
MEETING_STATUS_STARTED = "STARTED"
MEETING_STATUS_ENDED = "ENDED"
MEETING_STATUS_CREATED = "CREATED"
MEETING_STATUS_DELETED = "DELETED"


MEETING_STATUSES = (
    (MEETING_STATUS_ENDED, "Ended"),
    (MEETING_STATUS_STARTED, "Started"),
    (MEETING_STATUS_WAITING, "Waiting"),
    (MEETING_STATUS_CREATED, "Created"),
    (MEETING_STATUS_DELETED, "Deleted"),
)

MEETING_EVENT_STARTED = "meeting.started"
MEETING_EVENT_ENDED = "meeting.ended"
MEETING_EVENT_DELETED = "meeting.deleted"
MEETING_EVENT_UPDATED = "meeting.updated"
MEETING_EVENT_CREATED = "meeting.created"
MEETING_EVENT_RECOVERED = "meeting.recovered"
MEETING_EVENT_PERMANENTLY_DELETED = "meeting.permanently_deleted"
MEETING_REVIEW_OPERATION = "MEETING_REVIEW"

ZOOM_RECORDING_COMPLETED = "recording.completed"

