MEETING_STATUS_WAITING = "WAITING"
MEETING_STATUS_STARTED = "STARTED"
MEETING_STATUS_ENDED = "ENDED"
MEETING_STATUS_CREATED = "CREATED"
MEETING_STATUS_DELETED = "DELETED"


MEETING_STATUSES = (
    (MEETING_STATUS_ENDED, "Ended"),
    (MEETING_STATUS_STARTED, "Started"),
    (MEETING_STATUS_WAITING, "Waiting"),
    (MEETING_STATUS_CREATED, "Created"),
    (MEETING_STATUS_DELETED, "Deleted"),
)
