MEETING_STATUS_WAITING = "WAITING"
MEETING_STATUS_STARTED = "STARTED"
MEETING_STATUS_ENDED = "ENDED"
MEETING_STATUS_CREATED = "CREATED"
MEETING_STATUS_DELETED = "DELETED"


MEETING_STATUSES = (
    (MEETING_STATUS_ENDED, "Ended"),
    (MEETING_STATUS_STARTED, "Started"),
    (MEETING_STATUS_WAITING, "Waiting"),
    (MEETING_STATUS_CREATED, "Created"),
    (MEETING_STATUS_DELETED, "Deleted"),
)

MEETING_EVENT_STARTED = "meeting.started"
MEETING_EVENT_ENDED = "meeting.ended"
MEETING_EVENT_DELETED = "meeting.deleted"
MEETING_EVENT_UPDATED = "meeting.updated"
MEETING_EVENT_CREATED = "meeting.created"
MEETING_EVENT_RECOVERED = "meeting.recovered"
MEETING_EVENT_PERMANENTLY_DELETED = "meeting.permanently_deleted"

MEETING_EVENTS_CREATED = (
    MEETING_EVENT_CREATED,
    MEETING_EVENT_UPDATED,
    MEETING_EVENT_RECOVERED,
)

MEETING_EVENTS_DELETED = (
    MEETING_EVENT_DELETED,
    MEETING_EVENT_PERMANENTLY_DELETED,
)

MEETING_TRACKING_OPTION_YES = "YES"
MEETING_TRACKING_OPTION_NO = "NO"
MEETING_TRACKING_OPTION_NOT_SELECTED = "NOT_SELECTED"


MEETING_TRACKING_OPTIONS = (
    (MEETING_TRACKING_OPTION_NO, "No"),
    (MEETING_TRACKING_OPTION_YES, "Yes"),
    (MEETING_TRACKING_OPTION_NOT_SELECTED, "NOT_SELECTED"),
)
MEETING_SENTIMENT_GREAT = "GREAT"
MEETING_SENTIMENT_NOT_WELL = "NOT WELL"
MEETING_SENTIMENT_NA = "N/A"

MEETING_SENTIMENT_OPTIONS = (
    (MEETING_SENTIMENT_GREAT, "Great"),
    (MEETING_SENTIMENT_NOT_WELL, "Not Well"),
    (MEETING_SENTIMENT_NA, "N/A"),
)
