CRM_CHOICE_SALESFORCE = "SALESFORCE"
CRM_CHOICE_HUBSPOT = "HUBSPOT"
CRM_CHOICE_MANAGR = "MANAGR"

CRM_CHOICES = (
    (CRM_CHOICE_SALESFORCE, "Salesforce"),
    (CRM_CHOICE_HUBSPOT, "Hubspot"),
    (CRM_CHOICE_MANAGR, "Managr"),
)


CRM_FIELD_SYNC = "CRM_FIELD_SYNC"
CRM_RESOURCE_SYNC = "CRM_RESOURCE_SYNC"
