# Generated by Django 2.2.17 on 2021-01-13 20:15

from django.db import migrations, models
import django.db.models.deletion
import managr.utils.misc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to=managr.utils.misc.datetime_appended_filepath)),
                ('state', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255)),
                ('is_trial', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(default='#9B9B9B', help_text='hex code for color', max_length=255)),
                ('order', models.IntegerField()),
                ('is_closed', models.BooleanField()),
                ('is_won', models.BooleanField()),
                ('organization', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='organization.Organization')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, max_length=255, upload_to=managr.utils.misc.datetime_appended_filepath)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organization.Organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_account', to='organization.Account')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number_1', models.CharField(max_length=255)),
                ('phone_number_2', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.Account')),
            ],
            options={
                'ordering': ['first_name'],
                'unique_together': {('email', 'account')},
            },
        ),
    ]
