# Generated by Django 2.2.13 on 2020-07-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_externalsyncenabled',
            field=models.BooleanField(default=False),
        ),
    ]
