# Generated by Django 2.2.14 on 2020-07-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
    ]
