# Generated by Django 2.2.17 on 2021-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='parent_integration_id',
            field=models.CharField(blank=True, help_text='UUID from integration for parent account, saved in case of errors', max_length=255),
        ),
    ]
