# Generated by Django 2.2.14 on 2020-07-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_normalize_contact_emails"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE organization_contact set phone_number_1 =  REPLACE(REPLACE(REPLACE(REPLACE(phone_number_1, '(', ''), ')', ''), ' ',''), '-', '');"
                ),
                (
                    "UPDATE organization_contact set phone_number_2 =  REPLACE(REPLACE(REPLACE(REPLACE(phone_number_2, '(', ''), ')', ''), ' ',''), '-', '');"
                ),
                (
                    "UPDATE organization_contact set phone_number_1 = CONCAT('+1',phone_number_1) WHERE phone_number_1  !~ '^\+' AND phone_number_1 <> '';"
                ),
                (
                    "UPDATE organization_contact set phone_number_2 = CONCAT('+1',phone_number_2) WHERE phone_number_2  !~ '^\+' AND phone_number_2 <> '';"
                ),
            ],
            reverse_sql=[
                # adding this to make it reversable although it doesn't actually reverse
                ("SELECT phone_number_1 FROM organization_contact")
            ],
        )
    ]
