# Generated by Django 2.2.14 on 2020-07-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_normalize_contact_emails'),

    ]

    operations = [
    ]
