# Generated by Django 2.2.17 on 2021-01-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210119_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
