# Generated by Django 2.2.14 on 2020-07-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_clean_phone_numbers"),
        ("organization", "0003_merge_20200731_1834"),
    ]

    operations = []
