# Generated by Django 2.2.17 on 2021-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210120_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='value',
            field=models.CharField(blank=True, help_text='This may be use as a unique value, if it exists', max_length=255),
        ),
    ]
