# Generated by Django 2.2.15 on 2020-08-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_merge_20200731_1844'),
        ('organization', '0003_stage'),
    ]

    operations = [
    ]
