# Generated by Django 2.2.13 on 2020-08-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_auto_20200804_0229"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="organization.Organization",
            ),
        ),
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE organization_stage SET organization_id='' WHERE organization_id=NULL"
                )
            ],
            reverse_sql=[
                (
                    "UPDATE organization_stage SET organization_id=NULL WHERE organization_id=''"
                )
            ],
        ),
    ]
