# Generated by Django 2.2.15 on 2020-08-12 03:12

from django.db import migrations, models
import managr.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20200804_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(max_length=255, null=True, upload_to=managr.utils.misc.datetime_appended_filepath),
        ),
    ]
