# Generated by Django 2.2.13 on 2020-08-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_is_externalsyncenabled'),
        ('organization', '0006_auto_20200804_0229'),
    ]

    operations = [
    ]
