# Generated by Django 2.2.13 on 2020-08-31 20:56

from django.db import migrations, models
from django.core.management import call_command

fixture = "fixture"


def load_fixture(apps, schema_editor):
    call_command("loaddata", fixture, app_label="organization")


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_account_logo"),
    ]

    operations = [
        # first set the field to default to 0 to make sure all stages have a value
        migrations.AddField(
            model_name="stage", name="order", field=models.IntegerField(default=6),
        ),
        # run the fixture again to load the new default order for public
        migrations.RunPython(load_fixture),
    ]
