# Generated by Django 2.2.17 on 2021-01-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20210125_1716'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set(),
        ),
    ]
