# Generated by Django 2.2.13 on 2020-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_account_logo'),
        ('organization', '0007_merge_20200810_1341'),
    ]

    operations = [
    ]
