# Generated by Django 2.2.13 on 2020-09-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0008_stage_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="stage", options={"ordering": ["order"]},),
    ]
