# Generated by Django 2.2.17 on 2021-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_actionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
