# Generated by Django 2.2.13 on 2020-09-01 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_auto_20200901_1343"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="organization.Organization",
            ),
        ),
        migrations.RunSQL(
            sql=[
                'UPDATE organization_stage set organization_id = "" WHERE organization_id IS NULL;'
            ]
        ),
        migrations.AlterField(
            model_name="stage",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="organization.Organization",
            ),
        ),
    ]
