# Generated by Django 2.2.13 on 2020-09-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_merge_20200820_1341'),
        ('organization', '0010_auto_20200901_1351'),
    ]

    operations = [
    ]
