# Generated by Django 2.2.17 on 2021-01-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_stage_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
