# Generated by Django 2.2.15 on 2020-10-15 13:18

from django.db import migrations, models
import managr.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_merge_20200911_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(max_length=255, null=True, upload_to=managr.utils.misc.datetime_appended_filepath),
        ),
    ]
