# Generated by Django 2.2.17 on 2021-01-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20210127_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('OMITTED', 'Omitted'), ('PIPELINE', 'Pipeline'), ('BEST_CASE', 'Best Case'), ('COMMIT', 'Commit'), ('CLOSED', 'Closed')], max_length=255),
        ),
    ]
