# Generated by Django 2.2.17 on 2020-11-19 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_organization_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('email', 'organization')},
        ),
    ]
