# Generated by Django 2.2.17 on 2021-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_stage_forecast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='forecast_category',
            field=models.CharField(blank=True, choices=[('OMITTED', 'Omitted'), ('PIPELINE', 'Pipeline'), ('BESTCASE', 'Best Case'), ('FORECAST', 'Commit'), ('CLOSED', 'Closed')], max_length=255),
        ),
    ]
