# Generated by Django 2.2.18 on 2021-02-09 02:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20210202_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='account',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='url',
        ),
        migrations.AddField(
            model_name='account',
            name='secondary_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True),
        ),
    ]
