# Generated by Django 2.2.18 on 2021-02-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20210210_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile_phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
    ]
