# Generated by Django 2.2.18 on 2021-02-10 19:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_auto_20210210_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='secondary_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True),
        ),
    ]
