# Generated by Django 2.2.18 on 2021-02-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_contact_secondary_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='title',
        ),
    ]
