# Generated by Django 2.2.24 on 2021-08-26 14:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_remove_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='ignore_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='Email to ignore in meeting reviews', size=None),
        ),
    ]
