# Generated by Django 2.2.24 on 2021-12-10 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_organization_ignore_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ignore_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Email to ignore in meeting reviews', size=None),
        ),
    ]
