# Generated by Django 2.2.24 on 2021-12-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_pricebook2_pricebookentry_product2'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebookentry',
            name='external_pricebook',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255),
        ),
        migrations.AddField(
            model_name='pricebookentry',
            name='external_product',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255),
        ),
    ]
