# Generated by Django 2.2.24 on 2021-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_auto_20211201_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_products',
            field=models.BooleanField(default=False),
        ),
    ]
