# Generated by Django 2.2.24 on 2021-12-13 17:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0021_auto_20210309_1853'),
        ('organization', '0025_organization_has_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebook2',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricebooks', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='product2',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.Organization'),
        ),
        migrations.CreateModel(
            name='OpportunityLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('external_pricebook', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('external_product', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('external_opportunity', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=13, null=True)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_opportunitylineitem', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='opportunity.Opportunity')),
                ('pricebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='organization.Pricebook2')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='organization.Product2')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
