# Generated by Django 2.2.24 on 2021-12-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_auto_20211213_1727'),
        ('organization', '0023_auto_20211210_1944'),
    ]

    operations = [
    ]
