# Generated by Django 2.2.24 on 2021-12-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_merge_20211213_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
