# Generated by Django 2.2.24 on 2021-12-16 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_auto_20211216_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylineitem',
            name='external_pricebookentry',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='opportunitylineitem',
            name='pricebookentry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='organization.PricebookEntry'),
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='description',
            field=models.CharField(blank=True, default='Text', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='external_pricebook',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='pricebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='organization.Pricebook2'),
        ),
    ]
