# Generated by Django 2.2.24 on 2021-12-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0029_auto_20211216_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitylineitem',
            name='external_pricebook',
        ),
        migrations.RemoveField(
            model_name='opportunitylineitem',
            name='pricebook',
        ),
    ]
