# Generated by Django 2.2.24 on 2022-01-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_auto_20211216_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricebook2',
            name='description',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='product2',
            name='description',
            field=models.TextField(blank=True, max_length=225, null=True),
        ),
    ]
