# Generated by Django 2.2.24 on 2022-01-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_auto_20220111_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='opportunity.Opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='organization.Product2'),
        ),
    ]
