# Generated by Django 2.2.24 on 2022-01-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_auto_20220113_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='total_price',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
    ]
