# Generated by Django 2.2.24 on 2022-01-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_auto_20220117_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product2',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
