# Generated by Django 2.2.24 on 2022-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0035_auto_20220117_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricebook2',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product2',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
