# Generated by Django 2.2.24 on 2022-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_auto_20220119_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pricebook2',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product2',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stage',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
    ]
