# Generated by Django 2.2.24 on 2022-04-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_auto_20220119_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='number_of_allowed_users',
            field=models.IntegerField(default=1),
        ),
    ]
