# Generated by Django 2.2.24 on 2022-06-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0037_organization_number_of_allowed_users'),
        ('organization', '0037_auto_20220323_1731'),
    ]

    operations = [
    ]
