# Generated by Django 2.2.24 on 2022-10-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_team'),
        ('organization', '0038_merge_20220607_1332'),
    ]

    operations = [
    ]
