# Generated by Django 2.2.24 on 2022-12-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0039_merge_20221020_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylineitem',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_line_item', to='crm.BaseOpportunity'),
        ),
    ]
