# Generated by Django 2.2.24 on 2023-01-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0040_auto_20221222_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
