# Generated by Django 2.2.19 on 2023-01-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_organization_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='number_of_allowed_users',
            field=models.IntegerField(default=3),
        ),
    ]
