# Generated by Django 2.2.28 on 2023-08-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_auto_20230823_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='number_of_allowed_users',
            field=models.IntegerField(default=5),
        ),
    ]
