# Generated by Django 2.2.28 on 2023-12-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0044_auto_20230824_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='number_of_allowed_users',
            field=models.IntegerField(default=1),
        ),
    ]
