# Generated by Django 2.2.28 on 2023-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0045_auto_20231212_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='number_of_allowed_users',
            field=models.IntegerField(default=3),
        ),
    ]
