# Generated by Django 2.2.28 on 2024-06-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0046_auto_20231212_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='smtp_pass',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
