# Generated by Django 2.2.28 on 2024-10-15 19:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0047_auto_20240625_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
