# Generated by Django 2.2.15 on 2020-08-12 03:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0029_merge_20200807_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Content of the StoryReport')),
                ('datetime_generated', models.DateTimeField(help_text='date time when the report was populated with computed data', null=True)),
                ('generated_by', models.ForeignKey(help_text='Email notifying of report generation is to be sent to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_story_reports', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='story_reports', to='lead.Lead')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
