# Generated by Django 2.2.15 on 2020-09-22 16:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('date_range_preset', models.CharField(choices=[('THIS_MONTH', 'This Month'), ('LAST_MONTH', 'Last Month'), ('THIS_QUARTER', 'This Quarter'), ('LAST_QUARTER', 'Last Quarter'), ('THIS_YEAR', 'This Year'), ('LAST_YEAR', 'Last Year')], max_length=255)),
                ('date_range_from', models.DateTimeField()),
                ('date_range_to', models.DateTimeField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Content of the PerformanceReport')),
                ('datetime_generated', models.DateTimeField(help_text='date time when the report was populated with computed data', null=True)),
                ('generated_by', models.ForeignKey(help_text='Email notifying of report generation is to be sent to this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_performance_reports', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(help_text='If populated, refers to the representative that is the focus of the report. If it is NULL, it means that this is na organization-wide (all representatives) report.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
