services:
  - type: web
    name: managr-app
    env: docker
    plan: starter
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "managr.onrender.com"
      - key: CURRENT_DOMAIN
        value: "managr.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: managr-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: managr-redis

databases:
  - name: managr-db
    plan: free

redis:
  - name: managr-redis
    plan: free
