# Generated by Django 2.2.24 on 2022-06-07 17:49

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0038_merge_20220607_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255)),
                ('crm', models.CharField(choices=[('SALESFORCE', 'Salesforce'), ('HUBSPOT', 'Hubspot'), ('MANAGR', 'Managr')], default='SALESFORCE', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('external_owner', models.CharField(blank=True, max_length=255)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_baseaccount', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_accounts', to='organization.Organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='BaseContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255)),
                ('crm', models.CharField(choices=[('SALESFORCE', 'Salesforce'), ('HUBSPOT', 'Hubspot'), ('MANAGR', 'Managr')], default='SALESFORCE', max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('external_owner', models.CharField(blank=True, max_length=255)),
                ('external_account', models.CharField(blank=True, max_length=255)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.BaseAccount')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_basecontact', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='BaseOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True)),
                ('forecast_category', models.CharField(max_length=255, null=True)),
                ('close_date', models.DateField(null=True)),
                ('external_account', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('external_owner', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('stage', models.CharField(max_length=255, null=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.BaseAccount')),
                ('contacts', models.ManyToManyField(blank=True, related_name='contacts', to='crm.BaseContact')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_baseopportunity', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
