# Generated by Django 2.2.24 on 2022-06-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseaccount',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='basecontact',
            name='crm',
        ),
    ]
