# Generated by Django 2.2.24 on 2022-09-22 15:00

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20220609_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255)),
                ('crm_object', models.CharField(max_length=255, null=True)),
                ('api_name', models.CharField(max_length=255)),
                ('createable', models.BooleanField(default=False)),
                ('updateable', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(max_length=255)),
                ('display_value', models.CharField(blank=True, help_text='if this is a reference field we save the display value as well', max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('reference', models.BooleanField(default=False)),
                ('relationship_name', models.CharField(max_length=255, null=True)),
                ('reference_to_infos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='An of objects containing the API Name references', size=None)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=255, null=True), blank=True, default=list, help_text='if this is a custom managr field pass a dict of label, value, if this is not a custom managr field then construct the values dynamically', size=None)),
                ('is_public', models.BooleanField(default=False, help_text="Indicates whether or not this is a managr_created field that is not part of the user's object fields")),
                ('filterable', models.BooleanField(default=False, help_text='Indicates if we can filter queries against this field')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_objectfield', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
