# Generated by Django 2.2.24 on 2022-10-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import os
import json
from django.core.management import call_command


fixture = "crm.json"


def load_fixture(apps, schema_editor):
    """ helper function to load fixtures """
    call_command("loaddata", fixture, app_label="crm")


def remove_fixture(apps, schema_editor):
    """ reverse function to remove fixtures """
    fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../fixtures"))
    fixture_file_name = fixture
    fixture_file = os.path.join(fixture_dir, fixture_file_name)
    fixture_data = open(fixture_file, "rb")
    fixtures = json.loads(fixture_data.read())
    for fixt in fixtures:
        app_name, model_name = fixt["model"].split(".")
        my_model = apps.get_model(app_name, model_name)
        item = my_model.objects.filter(pk=fixt["pk"]).first()
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_objectfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectfield",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
