# Generated by Django 2.2.24 on 2022-10-10 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_objectfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectfield",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="object_fields",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
