# Generated by Django 2.2.24 on 2022-10-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_objectfield_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseopportunity',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='crm.BaseContact'),
        ),
    ]
