# Generated by Django 2.2.24 on 2023-02-08 15:47

# Generated by Django 2.2.24 on 2022-10-20 20:38

from django.db import migrations, models
import os
import json
from django.core.management import call_command

fixture = "crm.json"


def load_fixture(apps, schema_editor):
    """ helper function to load fixtures """
    call_command("loaddata", fixture, app_label="crm")


def remove_fixture(apps, schema_editor):
    """ reverse function to remove fixtures """
    fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../fixtures"))
    fixture_file_name = fixture
    fixture_file = os.path.join(fixture_dir, fixture_file_name)
    fixture_data = open(fixture_file, "rb")
    fixtures = json.loads(fixture_data.read())
    for fixt in fixtures:
        app_name, model_name = fixt["model"].split(".")
        my_model = apps.get_model(app_name, model_name)
        item = my_model.objects.filter(pk=fixt["pk"]).first()
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_auto_20221020_2105"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectfield",
            name="data_type_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(load_fixture, remove_fixture),
    ]
