# Generated by Django 2.2.24 on 2023-02-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20221020_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectfield',
            name='data_type_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
