# Generated by Django 2.2.12 on 2020-04-07 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The magic token is a randomly-generated uuid that can be used to identify the user in a non-password based login flow. '),
        ),
    ]
