# Generated by Django 2.2.12 on 2020-04-09 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The magic token is a randomly-generated uuid that can be used to identify the user in a non-password based login flow. '),
        ),
        migrations.AddField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 15, 26, 24, 725431, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.Organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited')], default='INVITED', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('LIMITED', 'LIMITED'), ('MANAGER', 'MANAGER')], default='MANAGER', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
