# Generated by Django 2.2.12 on 2020-05-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_serviceaccount',
            field=models.BooleanField(default=False),
        ),
    ]
