# Generated by Django 2.2.17 on 2021-01-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailauthaccount',
            name='linked_at',
        ),
    ]
