# Generated by Django 2.2.17 on 2021-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_emailauthaccount_linked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notify_at',
            field=models.DateTimeField(help_text='Set a time for the notification to be executed, if this is a reminder it can be something like 5 minutes before time if it is an email it can be the time the email is received ', null=True),
        ),
    ]
