# Generated by Django 2.2.12 on 2020-04-09 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200409_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 16, 38, 53, 880969, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
