# Generated by Django 2.2.17 on 2021-01-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210116_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('LEADERSHIP', 'Leadership'), ('FRONTLINE_MANAGER', 'Frontline Manager'), ('ACCOUNT_EXEC', 'Account Executive'), ('ACCOUNT MANAGER', 'Account Manager'), ('OPERATIONS', 'OPERATIONS'), ('ENABLEMENT', 'Enablement')], max_length=32),
        ),
    ]
