# Generated by Django 2.2.12 on 2020-06-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('core', '0003_auto_20200526_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('subject', models.TextField()),
                ('header', models.TextField()),
                ('body_html', models.TextField(help_text='WARNING: This content is not auto-escaped. Generally take care not to render user-provided data to avoid a possible HTML-injection.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email Templates',
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
