# Generated by Django 2.2.12 on 2020-06-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailtemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('user', 'name')},
        ),
    ]
