# Generated by Django 2.2.18 on 2021-02-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('MANAGER', 'REP')], default='REP', max_length=255),
        ),
    ]
