# Generated by Django 2.2.12 on 2020-04-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(blank=True, help_text='The datetime when the magic token is expired.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited')], default='INACTIVE', max_length=255),
        ),
    ]
