# Generated by Django 2.2.12 on 2020-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200407_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('INVITED', 'Invited')], default='INVITED', max_length=255),
        ),
    ]
