# Generated by Django 2.2.12 on 2020-06-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200602_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['name'], 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='header',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='organization',
        ),
    ]
