# Generated by Django 2.2.18 on 2021-02-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210205_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='NylasAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('account_id', models.CharField(max_length=255, null=True)),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('provider', models.CharField(max_length=255, null=True)),
                ('sync_state', models.CharField(help_text='sync state is managed by web_hook after it is set for the first time', max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nylas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email_address'],
            },
        ),
        migrations.DeleteModel(
            name='EmailAuthAccount',
        ),
    ]
