# Generated by Django 2.2.13 on 2020-07-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200602_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commit',
            field=models.PositiveIntegerField(default=0, help_text='Help text for User.commit'),
        ),
        migrations.AddField(
            model_name='user',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='Help text for User.quota'),
        ),
        migrations.AddField(
            model_name='user',
            name='upside',
            field=models.PositiveIntegerField(default=0, help_text='Help text for User.upside'),
        ),
    ]
