# Generated by Django 2.2.12 on 2020-04-09 20:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200409_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 20, 52, 24, 90231, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
