# Generated by Django 2.2.12 on 2020-04-08 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200408_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 4, 16, 54, 689171), help_text='The datetime when the magic token is expired.'),
        ),
    ]
