# Generated by Django 2.2.19 on 2021-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210224_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('REP', 'Rep')], default='REP', max_length=255),
        ),
    ]
