# Generated by Django 2.2.12 on 2020-04-08 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200408_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 14, 42, 11, 748384, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
