# Generated by Django 2.2.12 on 2020-04-09 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200407_1537'),
        ('core', '0008_auto_20200408_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 13, 45, 34, 423588, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
