# Generated by Django 2.2.14 on 2020-07-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('core', '0007_auto_20200720_2315'),
    ]

    operations = [
    ]
