# Generated by Django 2.2.14 on 2020-07-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_merge_20200727_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageauthaccount",
            name="date_created",
            field=models.DateTimeField(max_length=128),
        ),
        migrations.AlterField(
            model_name="messageauthaccount",
            name="date_updated",
            field=models.DateTimeField(max_length=128),
        ),
    ]
