# Generated by Django 2.2.12 on 2020-04-09 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200409_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accounts',
        ),
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 13, 57, 17, 973014, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
