# Generated by Django 2.2.14 on 2020-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200727_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageauthaccount',
            name='sid',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
