# Generated by Django 2.2.19 on 2021-06-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210609_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('REP', 'Rep'), ('SDR', 'SDR')], default='REP', max_length=255),
        ),
    ]
