# Generated by Django 2.2.12 on 2020-04-10 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200409_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 11, 53, 3, 643826, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
