# Generated by Django 2.2.24 on 2021-08-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210610_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='nylasauthaccount',
            name='event_calendar_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
