# Generated by Django 2.2.12 on 2020-04-10 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200410_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 12, 32, 59, 505916, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
