# Generated by Django 2.2.14 on 2020-07-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200727_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageauthaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
