# Generated by Django 2.2.24 on 2021-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_nylasauthaccount_event_calendar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nylasauthaccount',
            name='event_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
