# Generated by Django 2.2.19 on 2021-11-04 15:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210826_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_managr_configs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of activated Managr templates', size=None),
        ),
    ]
