# Generated by Django 2.2.14 on 2020-07-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20200731_1833"),
        ("core", "0012_messageauthaccount_phone_number"),
    ]

    operations = []
