# Generated by Django 2.2.15 on 2020-08-12 14:06

from django.db import migrations, models
import managr.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20200731_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(max_length=255, null=True, upload_to=managr.utils.misc.datetime_appended_filepath),
        ),
    ]
