# Generated by Django 2.2.13 on 2020-08-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_service_for'),
        ('core', '0013_merge_20200731_1844'),
    ]

    operations = [
    ]
