# Generated by Django 2.2.19 on 2021-11-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_activated_managr_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
    ]
