# Generated by Django 2.2.12 on 2020-04-10 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200410_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 18, 43, 22, 846326, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
