# Generated by Django 2.2.19 on 2021-11-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
