# Generated by Django 2.2.13 on 2020-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_profile_photo'),
        ('core', '0014_merge_20200810_1341'),
    ]

    operations = [
    ]
