# Generated by Django 2.2.24 on 2021-11-09 04:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import managr.core.constants


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211105_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminders',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=managr.core.constants.REMINDERS, help_text='Object for reminder setting', null=True),
        ),
    ]
