# Generated by Django 2.2.19 on 2021-11-08 23:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20211105_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activated_managr_configs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of activated Managr templates', size=None),
        ),
    ]
