# Generated by Django 2.2.13 on 2020-10-01 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20200820_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
