# Generated by Django 2.2.12 on 2020-04-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200413_1438'),
        ('core', '0015_auto_20200410_1843'),
    ]

    operations = [
    ]
