# Generated by Django 2.2.13 on 2020-09-29 16:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20200820_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, help_text='this will show up as a tooltip for the option')),
                ('default_value', models.BooleanField(default=True, help_text='All options are Boolean, the value here populates the default for the user')),
                ('user_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('LIMITED', 'LIMITED'), ('MANAGER', 'MANAGER'), ('INTEGRATION', 'INTEGRATION'), ('REP', 'REP'), ('ADMIN', 'ADMIN')], max_length=255), blank=True, default=list, help_text='An Array of user types that have access to this setting', size=None)),
                ('notification_type', models.CharField(choices=[('ALERT', 'ALERT'), ('EMAIL', 'EMAIL')], help_text='Email or Alert', max_length=255)),
            ],
            options={
                'ordering': ['-datetime_created'],
                'unique_together': {('title', 'notification_type')},
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('LIMITED', 'LIMITED'), ('MANAGER', 'MANAGER'), ('INTEGRATION', 'INTEGRATION'), ('REP', 'REP'), ('ADMIN', 'ADMIN')], default='MANAGER', max_length=255),
        ),
        migrations.CreateModel(
            name='NotificationSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField(help_text='If no option is selected it will take the default value')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.NotificationOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
                'unique_together': {('user', 'option')},
            },
        ),
    ]
