# Generated by Django 2.2.12 on 2020-04-20 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20200420_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 17, 34, 12, 221943, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
