# Generated by Django 2.2.24 on 2021-11-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_reminders'),
        ('core', '0016_auto_20211108_2351'),
    ]

    operations = [
    ]
