# Generated by Django 2.2.13 on 2020-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notificationselectionqueryset'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoption',
            name='key',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('EMAIL', 'Email'), ('ORGANIZATION', 'Organization'), ('TEXT', 'Text'), ('REPORT', 'Report'), ('REMINDER', 'Reminder')], help_text='select a static key to use when applying filter', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='title',
            field=models.CharField(help_text='Friendly Name', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='notificationoption',
            unique_together={('key', 'notification_type', 'user_groups')},
        ),
    ]
