# Generated by Django 2.2.12 on 2020-04-20 20:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200420_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 20, 16, 44, 832410, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
