# Generated by Django 2.2.13 on 2020-10-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201001_2234'),
        ('core', '0018_auto_20201001_2016'),
    ]

    operations = [
    ]
