# Generated by Django 2.2.24 on 2021-11-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_merge_20211110_2349'),
        ('core', '0018_auto_20211111_1851'),
    ]

    operations = [
    ]
