# Generated by Django 2.2.12 on 2020-04-21 02:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200420_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 21, 2, 27, 37, 283745, tzinfo=utc), help_text='The datetime when the magic token is expired.'),
        ),
    ]
