# Generated by Django 2.2.12 on 2020-04-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200421_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='magic_token_expiration',
            field=models.DateTimeField(help_text='The datetime when the magic token is expired.', null=True),
        ),
    ]
