# Generated by Django 2.2.13 on 2020-10-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20201013_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSelectionQuerySet',
        ),
    ]
