# Generated by Django 2.2.24 on 2021-12-09 15:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_meetingprepinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingprepinstance',
            name='event_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128),
        ),
    ]
