# Generated by Django 2.2.13 on 2020-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_notificationselectionqueryset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoption',
            name='key',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('EMAIL', 'Email'), ('ORGANIZATION', 'Organization'), ('TEXT', 'Text'), ('REPORT', 'Report'), ('REMINDER', 'Reminder'), ('OPPORTUNITY', 'Opportunity')], help_text='select a static key to use when applying filter', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='notificationoption',
            unique_together=set(),
        ),
    ]
