# Generated by Django 2.2.24 on 2021-12-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_meetingprepinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingprepinstance',
            name='form_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
