# Generated by Django 2.2.12 on 2020-05-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_is_invited'),
    ]

    operations = [
        migrations.RunSQL(sql=(

            "UPDATE core_user set is_active='t', is_invited='t' WHERE state='ACTIVE'; \
                UPDATE core_user set is_active='f', is_invited='t' WHERE state='INVITED';"


        ), reverse_sql=(

            "UPDATE core_user set state='ACTIVE', is_invited='t' WHERE is_active='t'; \
                        UPDATE core_user set state='INVITED' WHERE is_active='f' AND is_invited='t';"



        ))

    ]
