# Generated by Django 2.2.13 on 2020-10-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201014_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationoption',
            name='resource',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('ORGANIZATION', 'Organization'), ('REPORT', 'Report'), ('OPPORTUNITY', 'Opportunity')], help_text='select a resource to apply notification to', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationoption',
            name='key',
            field=models.CharField(blank=True, help_text='unique identifier for notification option', max_length=255, null=True),
        ),
    ]
