# Generated by Django 2.2.19 on 2021-12-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_meetingprepinstance_event_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingprepinstance',
            options={'ordering': ['datetime_created']},
        ),
    ]
