# Generated by Django 2.2.13 on 2020-10-18 21:06
import os
from sys import path
import json
from django.db import migrations, models
from django.core.management import call_command

fixture = "notification_options_fixture"


def load_fixture(apps, schema_editor):
    call_command("loaddata", fixture, app_label="core")


def remove_fixture(apps, schema_editor):
    """ reverse function to remove fixtures """
    fixture_dir = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../fixtures")
    )
    fixture_file_name = f"{fixture}.json"
    fixture_file = os.path.join(fixture_dir, fixture_file_name)
    fixture_data = open(fixture_file, "rb")
    fixtures = json.loads(fixture_data.read())
    for fixt in fixtures:
        app_name, model_name = fixt["model"].split(".")
        my_model = apps.get_model(app_name, model_name)
        item = my_model.objects.filter(pk=fixt["pk"]).first()
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_auto_20201018_2104"),
    ]

    operations = [migrations.RunPython(code=load_fixture, reverse_code=remove_fixture)]
