# Generated by Django 2.2.24 on 2022-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20211222_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingprepinstance',
            name='invocation',
            field=models.PositiveIntegerField(default=0, help_text='Keeps track of the number of times the meeting instance was called'),
        ),
    ]
