# Generated by Django 2.2.12 on 2020-05-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_set_active_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
