# Generated by Django 2.2.15 on 2020-10-21 15:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_load_notification_option_fixture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('LIMITED', 'LIMITED'), ('MANAGER', 'MANAGER'), ('INTEGRATION', 'INTEGRATION'), ('REP', 'REP'), ('ADMIN', 'ADMIN')], default='REP', max_length=255),
        ),
    ]
