# Generated by Django 2.2.12 on 2020-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_invited',
            field=models.BooleanField(default=True, max_length=255),
        ),
    ]
