# Generated by Django 2.2.24 on 2022-01-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0027_auto_20211217_1625'),
        ('core', '0023_meetingprepinstance_invocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingprepinstance',
            name='form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_prep_instance', to='slack.OrgCustomSlackFormInstance'),
        ),
    ]
