# Generated by Django 2.2.24 on 2022-05-06 16:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import managr.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_meetingprepinstance_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "clicks",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=managr.core.models.defaultClickActivity
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
