# Generated by Django 2.2.15 on 2020-10-21 17:38

from django.db import migrations
import managr.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201021_1510'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', managr.core.models.UserManager()),
            ],
        ),
    ]
