# Generated by Django 2.2.12 on 2020-05-11 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200504_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('account_id', models.CharField(max_length=255, null=True)),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('provider', models.CharField(max_length=255, null=True)),
                ('sync_state', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('linked_at', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_auth_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email_address'],
            },
        ),
    ]
