# Generated by Django 2.2.24 on 2022-04-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_meetingprepinstance_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'Salesforce'), ('HUBSPOT', 'Hubspot')], max_length=25, null=True),
        ),
    ]
