# Generated by Django 2.2.24 on 2022-05-20 16:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_forecast', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
