# Generated by Django 2.2.17 on 2020-12-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201021_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoption',
            name='notification_type',
            field=models.CharField(choices=[('ALERT', 'ALERT'), ('EMAIL', 'EMAIL'), ('SLACK', 'SLACK+')], help_text='Email or Alert', max_length=255),
        ),
    ]
