# Generated by Django 2.2.15 on 2020-11-19 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20201021_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSlackIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('slack_id', models.CharField(help_text='Slack ID of the User, for this workspace', max_length=255)),
                ('channel', models.CharField(help_text='Channel ID for the DM conversation between user and Managr bot', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
