# Generated by Django 2.2.24 on 2022-05-20 18:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userforecast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userforecast",
            name="state",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
