# Generated by Django 2.2.24 on 2022-10-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_user_crm'),
        ('core', '0030_auto_20220811_1944'),
    ]

    operations = [
    ]
