# Generated by Django 2.2.24 on 2023-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20221020_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='make_team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
