# Generated by Django 2.2.24 on 2023-04-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_make_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='notetemplate',
            name='type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('CHAT', 'Chat')], default='STANDARD', max_length=255),
        ),
    ]
