# Generated by Django 2.2.24 on 2023-07-13 23:04

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import managr.core.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_make_team_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('user_type', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('updated', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('generated', models.BooleanField(default=False)),
                ('data', managr.core.models.CustomJSONField(default='{}')),
                ('generated_title', models.CharField(max_length=100)),
                ('generated_type', models.CharField(max_length=100)),
                ('form_id', models.CharField(max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.Conversation')),
            ],
            options={
                'ordering': ['datetime_created'],
            },
        ),
    ]
