# Generated by Django 2.2.24 on 2023-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='error',
            field=models.TextField(null=True),
        ),
    ]
