# Generated by Django 2.2.24 on 2023-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_message_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='integration_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='resource',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
