# Generated by Django 2.2.24 on 2023-07-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20230714_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='form_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
