# Generated by Django 2.2.28 on 2023-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_message_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('PR', 'PR')], max_length=32),
        ),
    ]
