# Generated by Django 2.2.28 on 2023-08-17 13:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20230810_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
