# Generated by Django 2.2.28 on 2023-08-31 15:44

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import managr.utils.misc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_meta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=managr.utils.misc.datetime_appended_filepath)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
