# Generated by Django 2.2.28 on 2023-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_user_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('PR', 'PR'), ('DUAL', 'Dual')], max_length=32),
        ),
        migrations.DeleteModel(
            name='UserForecast',
        ),
    ]
