# Generated by Django 2.2.28 on 2023-09-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230901_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingPrepInstance',
        ),
    ]
