# Generated by Django 2.2.24 on 2023-09-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230901_1603'),
        ('core', '0039_report'),
    ]

    operations = [
    ]
