# Generated by Django 2.2.28 on 2023-09-13 05:28

from django.db import migrations, models
import managr.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20230907_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['datetime_created']},
        ),
        migrations.AlterField(
            model_name='report',
            name='main_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=managr.utils.misc.bucket_upload_filepath),
        ),
    ]
