# Generated by Django 2.2.28 on 2023-09-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20230913_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-datetime_created']},
        ),
    ]
