# Generated by Django 2.2.24 on 2023-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20230918_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='writing_style',
            field=models.TextField(blank=True, null=True),
        ),
    ]
