# Generated by Django 2.2.28 on 2023-11-22 20:48
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_user_writing_style"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activated_managr_configs",
        ),
        migrations.AddField(
            model_name="user",
            name="private_meta_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict, null=True
            ),
        ),
    ]
