# Generated by Django 2.2.28 on 2024-06-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_crawlerreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
