# Generated by Django 2.2.28 on 2024-07-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_googleaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
