# Generated by Django 2.2.28 on 2024-07-18 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_googleaccount_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
