# Generated by Django 2.2.28 on 2024-07-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20240718_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
