# Generated by Django 2.2.28 on 2024-08-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20240722_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerreport',
            name='blocked_urls',
            field=models.IntegerField(default=0),
        ),
    ]
