# Generated by Django 2.2.28 on 2024-08-20 04:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
        ('core', '0052_crawlerreport_blocked_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('json_result', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('text_result', models.TextField(blank=True, null=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='background_task.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
