# Generated by Django 2.2.28 on 2024-08-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_taskresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerreport',
            name='end_ts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crawlerreport',
            name='start_ts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
