# Generated by Django 2.2.28 on 2024-08-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20240823_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresults',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskresults',
            name='function_name',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskresults',
            name='task_id_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taskresults',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taskresults',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='background_task.Task'),
        ),
    ]
