# Generated by Django 2.2.28 on 2024-12-22 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20240829_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerreport',
            name='sources_not_ran',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None),
        ),
    ]
