# Generated by Django 2.2.28 on 2025-01-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_crawlerreport_sources_not_ran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='EST', max_length=255),
        ),
    ]
