# Generated by Django 2.2.28 on 2025-02-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20250120_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('link', 'LINK'), ('search', 'SEARCH'), ('followup', 'FOLLOWUP'), ('save', 'SAVE')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(choices=[('news', 'NEWS'), ('social', 'SOCIAL'), ('web', 'WEB'), ('omni', 'OMNI'), ('write', 'WRITE'), ('contacts', 'CONTACTS')], max_length=20)),
                ('query', models.TextField()),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='core.UserInteraction')),
            ],
        ),
        migrations.CreateModel(
            name='SaveInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(max_length=255)),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='core.UserInteraction')),
            ],
        ),
        migrations.CreateModel(
            name='LinkInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_link', models.TextField()),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.UserInteraction')),
            ],
        ),
        migrations.CreateModel(
            name='FollowupInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('previous', models.TextField(blank=True, null=True)),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.UserInteraction')),
            ],
        ),
    ]
