# Generated by Django 2.2.28 on 2025-02-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_followupinteraction_linkinteraction_saveinteraction_searchinteraction_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='linkinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='saveinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='save', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='searchinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='core.UserInteraction'),
        ),
    ]
