# Generated by Django 2.2.28 on 2025-02-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_followupinteraction_linkinteraction_saveinteraction_searchinteraction_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='linkinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='saveinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='searchinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search', to='core.UserInteraction'),
        ),
        migrations.AlterField(
            model_name='searchinteraction',
            name='search_type',
            field=models.CharField(choices=[('NEWS', 'news'), ('SOCIAL', 'social'), ('WEB', 'web'), ('OMNI', 'omni'), ('WRITE', 'write'), ('CONTACTS', 'contacts')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('LINK', 'link'), ('SEARCH', 'search'), ('FOLLOWUP', 'followup'), ('SAVE', 'save')], max_length=20),
        ),
    ]
