# Generated by Django 2.2.28 on 2025-02-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20250206_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveinteraction',
            name='interaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='core.UserInteraction'),
        ),
    ]
