# Generated by Django 2.2.28 on 2025-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20250206_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupinteraction',
            name='search_type',
            field=models.CharField(blank=True, choices=[('NEWS', 'News'), ('SOCIAL', 'Social'), ('WEB', 'Web'), ('OMNI', 'Omni'), ('WRITE', 'Write'), ('DISCOVER', 'Discover')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='searchinteraction',
            name='search_type',
            field=models.CharField(choices=[('NEWS', 'News'), ('SOCIAL', 'Social'), ('WEB', 'Web'), ('OMNI', 'Omni'), ('WRITE', 'Write'), ('DISCOVER', 'Discover')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('LINK', 'Link'), ('SEARCH', 'Search'), ('FOLLOWUP', 'Follow Up'), ('SAVE', 'Save')], max_length=20),
        ),
    ]
