# Generated by Django 2.2.17 on 2021-01-19 22:48

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFSyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('operations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="A dict of operations by type {'accounts':[]}")),
                ('failed_operations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="A dict of failed operations (limit 5 tries) {'accounts':[]}")),
                ('successful_operations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="A dict of successful operations by type {'accounts':[]}")),
                ('completed_operations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="A dict of all completed operations by type {'accounts':[]}")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
