# Generated by Django 2.2.17 on 2021-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0002_sfsyncoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='login_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='salesforce_account',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
