# Generated by Django 2.2.17 on 2021-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0004_salesforceauthaccount_refresh_token_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
