# Generated by Django 2.2.17 on 2021-01-29 14:54

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0005_salesforceauthaccount_is_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfsyncoperation',
            name='failed_operations',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='List of failed tasks as json since they are deleted', null=True, size=None),
        ),
    ]
