# Generated by Django 2.2.17 on 2021-02-02 19:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0006_sfsyncoperation_failed_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfsyncoperation',
            name='completed_operations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text="An Array of completed task id's", size=None),
        ),
    ]
