# Generated by Django 2.2.18 on 2021-02-05 21:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0007_auto_20210202_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='object_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True),
        ),
    ]
