# Generated by Django 2.2.19 on 2021-02-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0008_salesforceauthaccount_object_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SFObjectFieldsOperation",
            fields=[
                (
                    "sfsyncoperation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="salesforce.SFSyncOperation",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("salesforce.sfsyncoperation",),
        ),
        migrations.AddField(
            model_name="sfsyncoperation",
            name="operation_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
