# Generated by Django 2.2.19 on 2021-02-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0009_auto_20210226_1759"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesforceauthaccount",
            name="default_record_id",
            field=models.CharField(
                blank=True,
                help_text="The default record id should be the same for all objects and is used for picklist values",
                max_length=255,
            ),
        ),
    ]
