# Generated by Django 2.2.19 on 2021-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0009_auto_20210309_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingworkflow',
            options={'ordering': ['-datetime_created']},
        ),
    ]
