# Generated by Django 2.2.19 on 2021-03-12 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0010_auto_20210311_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingworkflow',
            name='failed_task_description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='list of dict failures', size=None),
        ),
        migrations.AlterField(
            model_name='sfsyncoperation',
            name='failed_operations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, help_text='List of failed tasks as that failed from task runner for uncaught exceptions after 5 tries', size=None),
        ),
    ]
