# Generated by Django 2.2.19 on 2021-03-01 19:33

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesforce', '0010_salesforceauthaccount_default_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SObjectField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('salesforce_object', models.CharField(max_length=255, null=True)),
                ('api_name', models.CharField(max_length=255)),
                ('custom', models.BooleanField(default=False)),
                ('createable', models.BooleanField(default=False)),
                ('updateable', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(max_length=255)),
                ('display_value', models.CharField(blank=True, help_text='if this is a reference field we save the display value as well', max_length=255)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
                ('length', models.PositiveIntegerField(default=0)),
                ('reference', models.BooleanField(default=False)),
                ('reference_to_infos', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='An of objects containing the API Name references', size=None)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=255, null=True), blank=True, default=list, help_text='if this is a custom managr field pass a dict of label, value, if this is not a custom managr field then construct the values dynamically', size=None)),
                ('is_public', models.BooleanField(default=False, help_text="Indicates whether or not this is a managr_created field that is not part of the user's object fields")),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_sobjectfield', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='salesforceauthaccount',
            name='object_fields',
        ),
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='sobjects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All resources we are retrieving', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SObjectValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('message', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('salesforce_object', models.CharField(max_length=255)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_sobjectvalidation', to=settings.AUTH_USER_MODEL)),
                ('salesforce_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_validations', to='salesforce.SalesforceAuthAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SObjectPicklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('attributes', models.CharField(blank=True, max_length=255)),
                ('valid_for', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picklist_options', to='salesforce.SObjectField')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_sobjectpicklist', to=settings.AUTH_USER_MODEL)),
                ('salesforce_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picklist_values', to='salesforce.SalesforceAuthAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sobjectfield',
            name='salesforce_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_fields', to='salesforce.SalesforceAuthAccount'),
        ),
    ]
