# Generated by Django 2.2.19 on 2021-03-30 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0011_auto_20210312_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SFResourceSync',
            fields=[
                ('sfsyncoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salesforce.SFSyncOperation')),
            ],
            options={
                'abstract': False,
            },
            bases=('salesforce.sfsyncoperation',),
        ),
    ]
