# Generated by Django 2.2.19 on 2021-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0011_auto_20210301_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobjectfield',
            name='relationship_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
