# Generated by Django 2.2.19 on 2021-03-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0012_sobjectfield_relationship_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobjectpicklist',
            name='picklist_for',
            field=models.CharField(blank=True, help_text='the name of the field this picklist is for, serializer will translate to actual field', max_length=255),
        ),
        migrations.AddField(
            model_name='sobjectpicklist',
            name='salesforce_object',
            field=models.CharField(default='Opportunity', max_length=255),
            preserve_default=False,
        ),
    ]
