# Generated by Django 2.2.19 on 2021-04-15 17:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0012_sfresourcesync'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='default_record_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text="Default Record Id's are obtained when initially getting fields we need this default record it to gather picklist values", max_length=500, null=True),
        ),
    ]
