# Generated by Django 2.2.19 on 2021-04-19 17:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0013_salesforceauthaccount_default_record_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='exclude_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text="Certain Fields are not available for query are retreived as part of the user's fields, these are tracked here and excluded on resyncs", max_length=1000, null=True),
        ),
    ]
