# Generated by Django 2.2.19 on 2021-03-02 00:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0013_auto_20210302_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobjectpicklist',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=255),
        ),
    ]
