# Generated by Django 2.2.19 on 2021-03-02 01:03

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0014_auto_20210302_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobjectpicklist',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='sobjectpicklist',
            name='label',
        ),
        migrations.RemoveField(
            model_name='sobjectpicklist',
            name='valid_for',
        ),
        migrations.RemoveField(
            model_name='sobjectpicklist',
            name='value',
        ),
        migrations.AddField(
            model_name='sobjectpicklist',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='An array of objects containing the values', size=None),
        ),
    ]
