# Generated by Django 2.2.19 on 2021-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0014_salesforceauthaccount_exclude_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobjectfield',
            name='filterable',
            field=models.BooleanField(default=False, help_text='Indicates if we can filter queries against this field'),
        ),
    ]
