# Generated by Django 2.2.19 on 2021-03-03 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0016_auto_20210224_1921'),
        ('salesforce', '0015_auto_20210302_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingWorkflow',
            fields=[
                ('sfsyncoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='salesforce.SFSyncOperation')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_workflow', to='zoom.ZoomMeeting')),
            ],
            options={
                'abstract': False,
            },
            bases=('salesforce.sfsyncoperation',),
        ),
    ]
