# Generated by Django 2.2.14 on 2020-09-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0016_auto_20210527_2303"),
    ]

    operations = [
        # changes made to model this migration will no longer work
    ]
