# Generated by Django 2.2.19 on 2021-03-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0016_meetingworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobjectpicklist',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picklist_options', to='salesforce.SObjectField'),
        ),
    ]
