# Generated by Django 2.2.14 on 2020-09-22 14:39
import os
from sys import path
import json
from django.db import migrations
from django.core.management import call_command


fixture = "fixture.json"


def load_fixture(apps, schema_editor):
    """ helper function to load fixtures """
    call_command("loaddata", fixture, app_label="salesforce")


def remove_fixture(apps, schema_editor):
    """ reverse function to remove fixtures """
    fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "../fixtures"))
    fixture_file_name = fixture
    fixture_file = os.path.join(fixture_dir, fixture_file_name)
    fixture_data = open(fixture_file, "rb")
    fixtures = json.loads(fixture_data.read())
    for fixt in fixtures:
        app_name, model_name = fixt["model"].split(".")
        my_model = apps.get_model(app_name, model_name)
        item = my_model.objects.filter(pk=fixt["pk"]).first()
        item.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0016_auto_20210527_2303"),
    ]

    operations = [
        migrations.RunPython(load_fixture, remove_fixture),
    ]
