# Generated by Django 2.2.19 on 2021-03-03 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0017_auto_20210303_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingworkflow',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoom.ZoomMeeting'),
        ),
    ]
