# Generated by Django 2.2.20 on 2021-06-16 15:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import managr.salesforce.models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0017_auto_20210528_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceauthaccount',
            name='sobjects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=managr.salesforce.models.getSobjectDefaults, help_text='All resources we are retrieving', max_length=500),
        ),
    ]
