# Generated by Django 2.2.23 on 2021-06-22 16:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0017_auto_20210528_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobjectfield',
            name='allow_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sobjectfield',
            name='default_filters',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=255, null=True), blank=True, default=list, size=None),
        ),
    ]
