# Generated by Django 2.2.19 on 2021-03-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0018_auto_20210303_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingworkflow',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='zoom.ZoomMeeting'),
        ),
    ]
