# Generated by Django 2.2.23 on 2021-06-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0018_auto_20210622_1622'),
        ('salesforce', '0018_auto_20210616_1521'),
    ]

    operations = [
    ]
