# Generated by Django 2.2.23 on 2021-06-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0018_auto_20210616_1521'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesforceauthaccount',
            constraint=models.UniqueConstraint(fields=('salesforce_id',), name='unique_salesforce_id'),
        ),
    ]
