# Generated by Django 2.2.19 on 2021-03-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0019_auto_20210303_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingworkflow',
            name='resource_id',
            field=models.CharField(blank=True, help_text='The id of the related resource unopinionated', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingworkflow',
            name='resource_type',
            field=models.CharField(blank=True, help_text='The class name of the resource', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meetingworkflow',
            name='slack_interaction',
            field=models.CharField(blank=True, help_text='Id of current slack message interaction, we will use this id to delete/update the interaction with its status', max_length=255),
        ),
        migrations.AddField(
            model_name='meetingworkflow',
            name='slack_view',
            field=models.CharField(blank=True, help_text='Id of slack view/modal, we will use this id to delete/update the form when using an async flow', max_length=255),
        ),
    ]
