# Generated by Django 2.2.20 on 2021-06-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0020_loadfixture'),
        ('salesforce', '0019_auto_20210623_1859'),
    ]

    operations = [
    ]
