# Generated by Django 2.2.19 on 2021-12-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0021_merge_20210630_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforceauthaccount',
            name='uses_products',
            field=models.BooleanField(default=False),
        ),
    ]
