# Generated by Django 2.2.24 on 2021-12-10 19:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0021_merge_20210630_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceauthaccount',
            name='exclude_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text="Certain Fields are not available for query are retreived as part of the user's fields, these are tracked here and excluded on resyncs", max_length=1000, null=True),
        ),
    ]
