# Generated by Django 2.2.24 on 2022-01-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0022_auto_20211210_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingworkflow',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='zoom.ZoomMeeting'),
        ),
    ]
