# Generated by Django 2.2.24 on 2022-01-13 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_meetingprepinstance_form'),
        ('salesforce', '0023_auto_20220106_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingworkflow',
            name='non_zoom_meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='core.MeetingPrepInstance'),
        ),
    ]
