# Generated by Django 2.2.24 on 2022-03-25 15:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salesforce", "0025_salesforceauthaccount_last_sync_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesforceauthaccount",
            name="extra_pipeline_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
    ]
