# Generated by Django 2.2.24 on 2022-09-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0027_auto_20220616_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobjectfield',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sobjectpicklist',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sobjectvalidation',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
    ]
