# Generated by Django 2.2.24 on 2022-06-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0026_salesforceauthaccount_extra_pipeline_fields'),
        ('salesforce', '0027_salesforceauthaccount_last_sync_time'),
    ]

    operations = [
    ]
