# Generated by Django 2.2.24 on 2022-10-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20221020_2105'),
        ('salesforce', '0028_auto_20220919_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='sobjectpicklist',
            name='object_field',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_picklist_options', to='crm.ObjectField'),
        ),
        migrations.AlterField(
            model_name='sobjectpicklist',
            name='field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picklist_options', to='salesforce.SObjectField'),
        ),
    ]
