# Generated by Django 2.2.24 on 2023-06-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0029_auto_20221027_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingworkflow',
            name='transcript_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingworkflow',
            name='transcript_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
