# Generated by Django 2.2.17 on 2021-01-13 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='This field is editable', max_digits=13)),
                ('forecast_category', models.CharField(choices=[('OMITTED', 'Omitted'), ('PIPELINE', 'Pipeline'), ('BEST_CASE', 'Best Case'), ('COMMIT', 'Commit'), ('CLOSED', 'Closed')], max_length=255)),
                ('expected_close_date', models.DateTimeField(blank=True)),
                ('primary_description', models.TextField(blank=True)),
                ('secondary_description', models.TextField(blank=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('stage_last_update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, choices=[('UPGRADE', 'Upgrade'), ('DOWNGRADE', 'Downgrade'), ('REPLACEMENT', 'Replacement'), ('NEW', 'New'), ('OTHER', 'Other')], max_length=255)),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='organization.Account')),
                ('claimed_by', models.ForeignKey(blank=True, help_text='Leads can only be closed by their claimed_by rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('final_score', models.IntegerField()),
                ('actions_score', models.IntegerField()),
                ('actions_insight', models.CharField(blank=True, max_length=255)),
                ('recent_action_score', models.IntegerField()),
                ('recent_action_insight', models.CharField(blank=True, max_length=255)),
                ('incoming_messages_score', models.IntegerField()),
                ('incoming_messages_insight', models.CharField(blank=True, max_length=255)),
                ('days_in_stage_score', models.IntegerField()),
                ('days_in_stage_insight', models.CharField(blank=True, max_length=255)),
                ('forecast_table_score', models.IntegerField()),
                ('forecast_table_insight', models.CharField(blank=True, max_length=255)),
                ('expected_close_date_score', models.IntegerField()),
                ('expected_close_date_insight', models.CharField(blank=True, max_length=255)),
                ('date_range_end', models.DateTimeField()),
                ('date_range_start', models.DateTimeField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='opportunity.Opportunity')),
                ('previous_score', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='opportunity.OpportunityScore')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='current_score',
            field=models.ForeignKey(blank=True, help_text='The has-many to this field should never be greater than 1. This FK is added for queryset purposes (see LeadFilterSet.by_score), even though Lead has-many LeadScores (see OpportunityScore.lead).', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='opportunity.OpportunityScore'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='linked_contacts',
            field=models.ManyToManyField(blank=True, related_name='leads', to='organization.Contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='organization.Stage'),
        ),
        migrations.CreateModel(
            name='ActionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_choices', to='organization.Organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
