# Generated by Django 2.2.17 on 2021-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='secondary_description',
            new_name='next_step',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='integration_id',
            field=models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
