# Generated by Django 2.2.17 on 2021-01-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_auto_20210119_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='current_score',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='stage_last_update',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.CharField(blank=True, help_text='Retrieved from Integration', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255),
        ),
    ]
