# Generated by Django 2.2.17 on 2021-01-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_auto_20210119_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='linked_contacts',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='organization.Contact'),
        ),
    ]
