# Generated by Django 2.2.17 on 2021-01-21 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_auto_20210119_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='external_account',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='external_owner',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='external_stage',
            field=models.CharField(blank=True, help_text='value from the integration', max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Leads can only be closed by their claimed_by rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='organization.Account'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Leads can only be closed by their claimed_by rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='organization.Stage'),
        ),
    ]
