# Generated by Django 2.2.17 on 2021-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_auto_20210121_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='last_activity_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_stage_update',
            field=models.DateTimeField(null=True),
        ),
    ]
