# Generated by Django 2.2.17 on 2021-01-21 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0006_auto_20210121_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='imported_by',
            field=models.ForeignKey(blank=True, help_text='Leads can only be closed by their claimed_by rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(null=True),
        ),
    ]
