# Generated by Django 2.2.17 on 2021-01-21 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0007_auto_20210121_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='expected_close_date',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='linked_contacts',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='primary_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='rating',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='organization.Account'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_opportunities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='organization.Stage'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
