# Generated by Django 2.2.17 on 2021-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_auto_20210121_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
    ]
