# Generated by Django 2.2.17 on 2021-01-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_opportunity_is_stale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionChoice',
        ),
    ]
