# Generated by Django 2.2.17 on 2021-01-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_delete_actionchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(choices=[('OMITTED', 'Omitted'), ('PIPELINE', 'Pipeline'), ('BESTCASE', 'Best Case'), ('FORECAST', 'Commit'), ('CLOSED', 'Closed')], max_length=255),
        ),
    ]
