# Generated by Django 2.2.17 on 2021-02-02 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0012_auto_20210129_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='imported_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imported_opportunity', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
