# Generated by Django 2.2.17 on 2021-02-02 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0013_auto_20210202_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='imported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_opportunity', to=settings.AUTH_USER_MODEL),
        ),
    ]
