# Generated by Django 2.2.18 on 2021-02-05 21:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_auto_20210203_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='next_step',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='type',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='secondary_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True),
        ),
    ]
