# Generated by Django 2.2.18 on 2021-02-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0017_auto_20210205_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='external_stage',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OpportunityScore',
        ),
    ]
