# Generated by Django 2.2.18 on 2021-02-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0018_auto_20210209_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13, null=True),
        ),
    ]
