# Generated by Django 2.2.18 on 2021-02-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0019_auto_20210217_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='title',
            new_name='name',
        ),
    ]
