# Generated by Django 2.2.19 on 2021-03-01 19:19

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0020_auto_20210225_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='reference_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, max_length=128), blank=True, default=list, help_text='An array of objects containing the API Name references and values for displaying', size=None),
        ),
    ]
