# Generated by Django 2.2.19 on 2021-03-02 20:06

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0021_opportunity_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('integration_id', models.CharField(blank=True, help_text='The UUID from the integration source', max_length=255)),
                ('integration_source', models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce')], max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('external_owner', models.CharField(blank=True, help_text='value from the integration', max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('secondary_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='All non primary fields that are on the model each org may have its own', max_length=500, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_lead', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
