# Generated by Django 2.2.24 on 2021-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0021_auto_20210309_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=13, null=True),
        ),
    ]
