# Generated by Django 2.2.24 on 2022-01-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0022_auto_20211230_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=30, null=True),
        ),
    ]
