# Generated by Django 2.2.24 on 2022-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0023_auto_20220114_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='integration_source',
            field=models.CharField(blank=True, choices=[('SALESFORCE', 'SalesForce'), ('HUBSPOT', 'Hubspot')], max_length=255),
        ),
    ]
