# Generated by Django 2.2.24 on 2022-07-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-datetime_created']},
        ),
    ]
