# Generated by Django 2.2.12 on 2020-04-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='lastupdate_at',
            new_name='last_update_at',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='last_updated',
            new_name='last_updated_at',
        ),
    ]
