# Generated by Django 2.2.12 on 2020-04-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20200409_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='closing_amount',
            field=models.PositiveIntegerField(default=0, help_text='This field is set at close and non-editable'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='This field is editable'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_for',
        ),
        migrations.AddField(
            model_name='note',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.Lead'),
        ),
    ]
