# Generated by Django 2.2.13 on 2020-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_auto_20200616_1507"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callnote",
            name="call_date",
            field=models.DateTimeField(help_text="The date the call occurred"),
        ),
    ]
