# Generated by Django 2.2.12 on 2020-04-10 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_auto_20200409_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('reminder', models.CharField(blank=True, max_length=255)),
                ('datetime_for', models.DateTimeField()),
                ('datetime_reminded', models.DateTimeField()),
                ('viewed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
