# Generated by Django 2.2.12 on 2020-04-10 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
    ]
