# Generated by Django 2.2.12 on 2020-04-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_remove_lead_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
