# Generated by Django 2.2.13 on 2020-06-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_auto_20200616_1629'),
        ('lead', '0003_auto_20200617_1957'),
    ]

    operations = [
    ]
