# Generated by Django 2.2.13 on 2020-06-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('lead', '0006_auto_20200617_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='linked_contacts',
            field=models.ManyToManyField(blank=True, related_name='actions', to='organization.Contact'),
        ),
    ]
