# Generated by Django 2.2.13 on 2020-06-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_action_created_by'),
        ('lead', '0006_merge_20200618_1547'),
    ]

    operations = [
    ]
