# Generated by Django 2.2.13 on 2020-06-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_merge_20200618_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
