# Generated by Django 2.2.12 on 2020-04-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='meta',
            field=models.CharField(blank=True, help_text='Extra details about activity', max_length=255),
        ),
        migrations.AlterField(
            model_name='list',
            name='leads',
            field=models.ManyToManyField(blank=True, to='lead.Lead'),
        ),
    ]
