# Generated by Django 2.2.13 on 2020-06-18 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0010_lead_status_last_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status_last_update",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
