# Generated by Django 2.2.12 on 2020-04-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_note_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='forecast',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='rank',
            new_name='rating',
        ),
    ]
