# Generated by Django 2.2.13 on 2020-06-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0011_auto_20200618_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivitylog',
            name='activity',
            field=models.CharField(choices=[('Lead.CREATED', 'Lead Created'), ('Lead.UPDATED', 'Lead Updated'), ('Lead.DELETED', 'Lead Deleted'), ('Lead.CLAIMED', 'Lead Claimed'), ('Lead.RELEASED', 'Lead Released'), ('Lead.CLOSED', 'Lead Closed'), ('Note.CREATED', 'Note Created'), ('Note.UPDATED', 'Note Updated'), ('Note.DELETED', 'Note Deleted'), ('CallNote.CREATED', 'Call Note Created'), ('CallNote.UPDATED', 'Call Note Updated'), ('CallNote.DELETED', 'Call Note Deleted'), ('File.CREATED', 'File Created'), ('File.UPDATED', 'File Updated'), ('File.DELETED', 'File Deleted'), ('Reminder.CREATED', 'Reminder Created'), ('Reminder.UPDATED', 'Reminder Updated'), ('Reminder.DELETED', 'Reminder Deleted'), ('Action.CREATED', 'Action Created'), ('Action.UPDATED', 'Action Updated'), ('Action.DELETED', 'Action Deleted'), ('LeadEmail.SENT', 'Email Sent'), ('LeadEmail.Received', 'Email Received')], help_text='records any actions taken on a lead', max_length=255),
        ),
        migrations.CreateModel(
            name='LeadEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('thread_id', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_threads', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='lead.Lead')),
            ],
        ),
    ]
