# Generated by Django 2.2.12 on 2020-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0012_auto_20200421_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
