# Generated by Django 2.2.13 on 2020-07-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_auto_20200622_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateTimeField(null=True),
        ),
    ]
