# Generated by Django 2.2.12 on 2020-04-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0013_auto_20200421_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
