# Generated by Django 2.2.12 on 2020-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0014_auto_20200421_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='reminder',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='viewed',
        ),
        migrations.AddField(
            model_name='reminder',
            name='action_taken',
            field=models.CharField(choices=[('SNOOZE', 'Snooze'), ('VIEWED', 'Viewed')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='action_taken_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
