# Generated by Django 2.2.13 on 2020-07-13 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0014_lead_expected_close_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadactivitylog",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="lead.Lead",
            ),
        ),
    ]
