# Generated by Django 2.2.13 on 2020-07-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_auto_20200713_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-notify_at']},
        ),
    ]
