# Generated by Django 2.2.12 on 2020-04-22 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_auto_20200421_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('notify_at', models.DateTimeField(help_text='Set a time for the notification to be executed, if this is a reminder it can be something like 5 minutes before time                                        if it is an email it can be the time the email is received ', null=True)),
                ('notified_at', models.DateTimeField(help_text='date time when the notification was executed', null=True)),
                ('title', models.CharField(help_text='a title for the notification', max_length=255, null=True)),
                ('action_taken', models.CharField(choices=[('SNOOZE', 'Snooze'), ('VIEWED', 'Viewed')], help_text='a notification can either be viewed or snoozed', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='action_taken_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='datetime_reminded',
        ),
        migrations.AddField(
            model_name='reminder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lead.Lead'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='lead.Notification'),
        ),
    ]
