# Generated by Django 2.2.12 on 2020-04-21 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_lead'),
        ('lead', '0015_auto_20200421_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('action_detail', models.CharField(blank=True, max_length=255)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lead.ActionChoice')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
