# Generated by Django 2.2.12 on 2020-04-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_action_actionchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='lead.Lead'),
        ),
    ]
