# Generated by Django 2.2.13 on 2020-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('lead', '0016_auto_20200715_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='leademail',
            name='linked_contacts',
            field=models.ManyToManyField(blank=True, related_name='email_activity_logs', to='organization.Contact'),
        ),
        migrations.AlterField(
            model_name='leadactivitylog',
            name='activity',
            field=models.CharField(choices=[('Lead.CREATED', 'Lead Created'), ('Lead.UPDATED', 'Lead Updated'), ('Lead.DELETED', 'Lead Deleted'), ('Lead.CLAIMED', 'Lead Claimed'), ('Lead.RELEASED', 'Lead Released'), ('Lead.CLOSED', 'Lead Closed'), ('Note.CREATED', 'Note Created'), ('Note.UPDATED', 'Note Updated'), ('Note.DELETED', 'Note Deleted'), ('CallNote.CREATED', 'Call Note Created'), ('CallNote.UPDATED', 'Call Note Updated'), ('CallNote.DELETED', 'Call Note Deleted'), ('File.CREATED', 'File Created'), ('File.UPDATED', 'File Updated'), ('File.DELETED', 'File Deleted'), ('Reminder.CREATED', 'Reminder Created'), ('Reminder.UPDATED', 'Reminder Updated'), ('Reminder.DELETED', 'Reminder Deleted'), ('Action.CREATED', 'Action Created'), ('Action.UPDATED', 'Action Updated'), ('Action.DELETED', 'Action Deleted'), ('LeadEmail.SENT', 'Email Sent'), ('LeadEmail.RECEIVED', 'Email Received')], help_text='records any actions taken on a lead', max_length=255),
        ),
    ]
