# Generated by Django 2.2.12 on 2020-04-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_auto_20200422_1702'),
        ('lead', '0017_auto_20200421_1845'),
    ]

    operations = [
    ]
