# Generated by Django 2.2.13 on 2020-07-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_auto_20200716_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='notification',
        ),
    ]
