# Generated by Django 2.2.12 on 2020-04-23 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import managr.utils.misc


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_auto_20200421_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='type',
            new_name='doc_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='last_update_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='uploaded_to',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to=managr.utils.misc.datetime_appended_filepath),
        ),
        migrations.AddField(
            model_name='file',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='actionchoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_choices', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
