# Generated by Django 2.2.13 on 2020-07-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0018_remove_reminder_notification"),
        ("lead", "0015_auto_20200720_2028"),
    ]

    operations = []
