# Generated by Django 2.2.12 on 2020-04-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0019_reminder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_reminders', to=settings.AUTH_USER_MODEL),
        ),
    ]
