# Generated by Django 2.2.13 on 2020-07-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0019_merge_20200721_2106"),
        ("lead", "0019_auto_20200722_1424"),
    ]

    operations = []
