# Generated by Django 2.2.13 on 2020-07-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0020_merge_20200724_1409"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="forecast",
            field=models.CharField(
                choices=[
                    ("50/50", "50/50"),
                    ("NA", "NA"),
                    ("STRONG", "Strong"),
                    ("FUTURE", "Future"),
                    ("VERBAL", "Verbal"),
                    ("CLOSED", "Closed"),
                ],
                default="NA",
                max_length=255,
                null=True,
            ),
        ),
    ]
