# Generated by Django 2.2.14 on 2020-07-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0020_merge_20200724_1409"),
        ("lead", "0020_leadmessage_direction"),
    ]

    operations = []
