# Generated by Django 2.2.12 on 2020-04-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0020_auto_20200422_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='organization',
        ),
        migrations.AlterField(
            model_name='actionchoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_choices', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='list',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='lists', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
