# Generated by Django 2.2.12 on 2020-04-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_auto_20200423_1505'),
        ('lead', '0018_auto_20200423_1619'),
    ]

    operations = [
    ]
