# Generated by Django 2.2.14 on 2020-08-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ migration to change all statuses to static ones since it is a foreign related key """

    dependencies = [
        ('lead', '0021_auto_20200728_0050'),
        ('organization', '0003_stage'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("UPDATE lead_lead SET status = 'fe89a6fd-f049-4b23-a059-86d45c12b14b' WHERE status='CLOSED';"),
                ("UPDATE lead_lead SET status = NULL WHERE status <> 'fe89a6fd-f049-4b23-a059-86d45c12b14b' AND status IS NOT  NULL;")
            ]
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='leads', to='organization.Stage'),
        ),
    ]
