# Generated by Django 2.2.14 on 2020-08-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ migration to change all statuses to static ones since it is a foreign related key """

    dependencies = [
        ("lead", "0021_auto_20200728_0050"),
        ("organization", "0003_stage"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "UPDATE lead_lead SET status = 'fe89a6fd-f049-4b23-a059-86d45c12b14b' WHERE status='CLOSED';"
                ),
                (
                    "UPDATE lead_lead SET status ='34066d79-824b-4541-9f4e-6be1a9f602bb' WHERE status='LEAD';"
                ),
                (
                    "UPDATE lead_lead SET status ='6407b7a1-a877-44e2-979d-1effafec5035' WHERE status='READY';"
                ),
                (
                    "UPDATE lead_lead SET status ='2b6d451f-c1db-4da3-9bde-632c6150804e' WHERE status='BOOKED';"
                ),
                (
                    "UPDATE lead_lead SET status ='ea67dcc4-cc7d-4ad9-a859-d62b1d2c6f8d' WHERE status='DEMO';"
                ),
                (
                    "UPDATE lead_lead SET status ='d57310d2-cf68-4c54-af40-8eac8e5a0825' WHERE status='TRIAL';"
                ),
                (
                    "UPDATE lead_lead SET status ='a61b108d-4259-4407-9a25-a62e8b2df460' WHERE status='WAITING';"
                ),
                (
                    "UPDATE lead_lead SET status ='36be069d-7d39-4b7f-a339-aa7c0a27085d' WHERE status='LOST';"
                ),
            ]
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="organization.Stage",
            ),
        ),
    ]
