# Generated by Django 2.2.14 on 2020-07-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0021_auto_20200728_0050'),

    ]

    operations = [
    ]
