# Generated by Django 2.2.14 on 2020-07-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0022_merge_20200731_1834"),
        ("lead", "0022_auto_20200729_2236"),
    ]

    operations = []
