# Generated by Django 2.2.12 on 2020-04-23 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0022_merge_20200423_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contract',
        ),
        migrations.AlterField(
            model_name='lead',
            name='claimed_by',
            field=models.ForeignKey(help_text='Leads can only be closed by their claimed_by rep', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
