# Generated by Django 2.2.12 on 2020-04-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0023_auto_20200423_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='lead.File'),
        ),
    ]
