# Generated by Django 2.2.15 on 2020-08-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0022_auto_20200803_1656"),
        ("lead", "0023_merge_20200731_1844"),
    ]

    operations = []
