# Generated by Django 2.2.15 on 2020-08-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0022_set_reminders_null'),
        ('lead', '0023_merge_20200731_1844'),
    ]

    operations = [
    ]
