# Generated by Django 2.2.12 on 2020-04-24 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200422_1525'),
        ('lead', '0024_lead_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lists', to='api.Organization'),
        ),
    ]
