# Generated by Django 2.2.15 on 2020-08-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0024_merge_20200804_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadmessage',
            options={'ordering': ['-datetime_created']},
        ),
    ]
