# Generated by Django 2.2.13 on 2020-08-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0022_set_reminders_null"),
        ("lead", "0025_auto_20200804_0229"),
    ]

    operations = []
