# Generated by Django 2.2.12 on 2020-04-24 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0025_list_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='organization',
        ),
    ]
