# Generated by Django 2.2.12 on 2020-04-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_remove_list_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='contract',
        ),
        migrations.AlterField(
            model_name='file',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='lead.Lead'),
        ),
    ]
