# Generated by Django 2.2.12 on 2020-04-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0026_remove_list_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='list',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='last_updated_at',
        ),
    ]
