# Generated by Django 2.2.13 on 2020-08-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0024_merge_20200805_1505"),
        ("lead", "0026_merge_20200805_1420"),
    ]

    operations = []
