# Generated by Django 2.2.13 on 2020-08-06 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0027_merge_20200805_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnote',
            name='created_for',
            field=models.ForeignKey(help_text='The Lead that this note was created for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_callnotes', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_for',
            field=models.ForeignKey(help_text='The Lead that this note was created for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_for',
            field=models.ForeignKey(help_text='The Lead that this note was created for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_reminders', to='lead.Lead'),
        ),
    ]
