# Generated by Django 2.2.12 on 2020-04-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0027_auto_20200425_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='last_updated_at',
        ),
    ]
