# Generated by Django 2.2.12 on 2020-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0027_auto_20200428_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
