# Generated by Django 2.2.12 on 2020-05-04 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0028_remove_lead_last_updated_at'),
        ('lead', '0027_auto_20200428_0855'),
    ]

    operations = [
    ]
