# Generated by Django 2.2.13 on 2020-08-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0028_auto_20200806_1319"),
        ("lead", "0026_merge_20200805_1508"),
    ]

    operations = []
