# Generated by Django 2.2.13 on 2020-08-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0028_auto_20200806_1319"),
        ("lead", "0015_auto_20200713_0107"),
    ]

    operations = []
