# Generated by Django 2.2.13 on 2020-08-14 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0029_merge_20200807_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
