# Generated by Django 2.2.12 on 2020-05-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0029_merge_20200504_0323'),
        ('lead', '0028_reminder_viewed'),
    ]

    operations = [
    ]
