# Generated by Django 2.2.13 on 2020-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0029_merge_20200810_1341"),
        ("lead", "0029_merge_20200807_1449"),
    ]

    operations = []
