# Generated by Django 2.2.12 on 2020-05-07 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0030_merge_20200507_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-datetime_for']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='lead',
        ),
        migrations.AddField(
            model_name='reminder',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_reminder', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='primary_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_note', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lead_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_reminder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lead_reminder', to=settings.AUTH_USER_MODEL),
        ),
    ]
