# Generated by Django 2.2.13 on 2020-08-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0030_auto_20200814_1500'),
        ('lead', '0030_merge_20200810_1443'),
    ]

    operations = [
    ]
