# Generated by Django 2.2.13 on 2020-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0031_auto_20200825_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnote',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
