# Generated by Django 2.2.12 on 2020-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0032_callnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnote',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_callnotes', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_reminders', to='lead.Lead'),
        ),
    ]
