# Generated by Django 2.2.13 on 2020-08-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0032_auto_20200831_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_detail',
            field=models.TextField(blank=True),
        ),
    ]
