# Generated by Django 2.2.13 on 2020-09-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0033_auto_20200831_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadmessage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
