# Generated by Django 2.2.12 on 2020-05-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0033_auto_20200511_0833'),
        ('lead', '0033_auto_20200508_0430'),
    ]

    operations = [
    ]
