# Generated by Django 2.2.13 on 2020-09-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0034_auto_20200901_1510'),
        ('lead', '0031_merge_20200828_1549'),
    ]

    operations = [
    ]
