# Generated by Django 2.2.12 on 2020-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0034_auto_20200512_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='datetime_for',
            field=models.DateTimeField(null=True),
        ),
    ]
