# Generated by Django 2.2.15 on 2020-09-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0035_merge_20200911_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_size',
            field=models.CharField(choices=[('1-50', '1-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5000+', '5000+')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor_description',
            field=models.CharField(blank=True, help_text="Describes the value chosen in the Lead's competitor field", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom',
            field=models.CharField(blank=True, help_text='Custom field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture'), ('APPAREL', 'Apparel'), ('BANKING', 'Banking'), ('BIOTECHNOLOGY', 'Biotechnology'), ('CHEMICALS', 'Chemicals'), ('COMMUNICATIONS', 'Communications'), ('CONSTRUCTION', 'Construction'), ('CONSULTING', 'Consulting'), ('EDUCATION', 'Education'), ('ELECTRONICS', 'Electronics'), ('ENERGY', 'Energy'), ('ENGINEERING', 'Engineering'), ('ENTERTAINMENT', 'Entertainment'), ('ENVIRONMENTAL', 'Environmental'), ('FINANCE', 'Finance'), ('FOOD_AND_BEVERAGE', 'Food & Beverage'), ('GOVERNMENT', 'Government'), ('HEALTHCARE', 'Healthcare'), ('HOSPITALITY', 'Hospitality'), ('INSURANCE', 'Insurance'), ('MACHINERY', 'Machinery'), ('MANUFACTURING', 'Manufacturing'), ('MEDIA', 'Media'), ('NOT_FOR_PROFIT', 'Not for Profit'), ('RECREATION', 'Recreation'), ('RETAIL', 'Retail'), ('SHIPPING', 'Shipping'), ('TECHNOLOGY', 'Technology'), ('TELECOMMUNICATIONS', 'Telecommunications'), ('TRANSPORTATION', 'Transportation'), ('UTILITIES', 'Utilities'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('MQL', 'MQL'), ('SQL', 'SQL'), ('OTHER', 'Other')], max_length=255, null=True),
        ),
    ]
