# Generated by Django 2.2.15 on 2020-09-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0035_merge_20200911_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company_size',
            field=models.CharField(choices=[('1-50', '1-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5000+', '5000+')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='competitor_description',
            field=models.CharField(blank=True, help_text="Describes the value chosen in the Lead's competitor field", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom',
            field=models.CharField(blank=True, help_text='Custom field', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.CharField(choices=[('Agriculture', 'Agriculture'), ('Apparel', 'Apparel'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Chemicals', 'Chemicals'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Environmental', 'Environmental'), ('Finance', 'Finance'), ('Food & Beverage', 'Food & Beverage'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Insurance', 'Insurance'), ('Machinery', 'Machinery'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media'), ('Not for Profit', 'Not for Profit'), ('Recreation', 'Recreation'), ('Retail', 'Retail'), ('Shipping', 'Shipping'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='type',
            field=models.CharField(choices=[('MQL', 'MQL'), ('SQL', 'SQL'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
