# Generated by Django 2.2.15 on 2020-10-13 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0036_auto_20200917_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callnote',
            name='created_for',
            field=models.ForeignKey(help_text='The Lead that this note was created for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_callnotes', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='claimed_by',
            field=models.ForeignKey(help_text='Leads can only be closed by their claimed_by rep', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claimed_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadactivitylog',
            name='action_taken_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadactivitylog',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_for',
            field=models.ForeignKey(help_text='The Lead that this note was created for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='lead.Lead'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_for',
            field=models.ForeignKey(help_text='The Lead that this note was created for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_reminders', to='lead.Lead'),
        ),
    ]
