# Generated by Django 2.2.12 on 2020-05-13 11:27

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0036_auto_20200513_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
        migrations.AlterField(
            model_name='lead',
            name='closing_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
    ]
