# Generated by Django 2.2.13 on 2020-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0037_auto_20201013_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REMINDER', 'Reminder'), ('EMAIL', 'Email'), ('SYSTEM', 'System'), ('EMAIL_OPENED', 'Email Opened'), ('OPPORTUNITY.INACTIVE', 'Opportunity Inactive'), ('OPPORTUNITY.STALLED_IN_STAGE', 'Opportunity Stalled in Stage'), ('OPPORTUNITY.LAPSED_EXPECTED_CLOSE_DATE_1', 'Opportunity Lapsed Expected Close Date By 1 day or more'), ('OPPORTUNITY.LAPSED_EXPECTED_CLOSE_DATE_14', 'Opportunity Lapsed Expected Close Date By 14 days or more'), ('OPPORTUNITY.LAPSED_EXPECTED_CLOSE_DATE_30', 'Opportunity Lapsed Expected Close Date By 30 days or more')], help_text='type of Notification being created', max_length=255, null=True),
        ),
    ]
