# Generated by Django 2.2.12 on 2020-05-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0037_auto_20200513_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='amount_currency',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='closing_amount_currency',
        ),
        migrations.AlterField(
            model_name='lead',
            name='amount',
            field=models.PositiveIntegerField(default=0, help_text='This field is editable'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='closing_amount',
            field=models.PositiveIntegerField(default=0, help_text='This field is set at close and non-editable'),
        ),
    ]
