# Generated by Django 2.2.15 on 2020-10-16 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0037_auto_20201013_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveIntegerField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='lead.Lead')),
            ],
            options={
                'ordering': ['-datetime_created'],
            },
        ),
    ]
