# Generated by Django 2.2.15 on 2020-10-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0038_leadscore'),
        ('lead', '0038_auto_20201014_1841'),
    ]

    operations = [
    ]
