# Generated by Django 2.2.15 on 2020-10-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0039_merge_20201019_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadscore',
            old_name='upper_bound',
            new_name='date_range_end',
        ),
        migrations.RenameField(
            model_name='leadscore',
            old_name='lower_bound',
            new_name='date_range_start',
        ),
        migrations.RemoveField(
            model_name='leadscore',
            name='score',
        ),
        migrations.AddField(
            model_name='leadscore',
            name='actions_insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='actions_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadscore',
            name='days_in_stage_insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='days_in_stage_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadscore',
            name='expected_close_date_insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='expected_close_date_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadscore',
            name='forecast_table_insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='forecast_table_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadscore',
            name='incoming_messages_insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='incoming_messages_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadscore',
            name='previous_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lead.LeadScore'),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='recent_action_insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadscore',
            name='recent_action_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
