# Generated by Django 2.2.15 on 2020-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0040_auto_20201021_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current_score',
            field=models.ForeignKey(help_text='The has-many to this field should never be greater than 1. This FK is added for queryset purposes (see LeadFilterSet.by_score), even though Lead has-many LeadScores (see LeadScore.lead).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='lead.LeadScore'),
        ),
    ]
