# Generated by Django 2.2.15 on 2020-10-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0041_lead_current_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadscore',
            name='final_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
