# Generated by Django 2.2.15 on 2020-10-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0042_leadscore_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This field is editable', max_digits=13),
        ),
        migrations.AlterField(
            model_name='lead',
            name='closing_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='This field is set at close and non-editable', max_digits=13),
        ),
    ]
