# Generated by Django 2.2.17 on 2020-12-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0043_auto_20201023_1411"),
    ]

    operations = [
        # first add the field
        migrations.AddField(
            model_name="notification",
            name="notification_class",
            field=models.CharField(
                blank=True,
                choices=[("ALERT", "ALERT"), ("EMAIL", "EMAIL"), ("SLACK", "SLACK+")],
                help_text="Classification of notification, email, alert, slack",
                max_length=255,
                null=True,
            ),
        ),
        # then add a default
        migrations.RunSQL(
            sql=["UPDATE lead_notification SET notification_class='ALERT';"],
        ),
        # then set the column to not null nor blank
        migrations.AlterField(
            model_name="notification",
            name="notification_class",
            field=models.CharField(
                choices=[("ALERT", "ALERT"), ("EMAIL", "EMAIL"), ("SLACK", "SLACK+")],
                help_text="Classification of notification, email, alert, slack",
                max_length=255,
            ),
        ),
    ]
