# Generated by Django 2.2.17 on 2020-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0044_notification_notification_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_class',
            field=models.CharField(choices=[('ALERT', 'ALERT'), ('EMAIL', 'EMAIL'), ('SLACK', 'SLACK')], help_text='Classification of notification, email, alert, slack', max_length=255),
        ),
    ]
