# Generated by Django 2.2.28 on 2023-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
