# Generated by Django 2.2.28 on 2023-08-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_auto_20230810_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='type',
            field=models.CharField(choices=[('NEWS', 'News'), ('SOCIAL_MEDIA', 'Social Media'), ('MIXED', 'Mixed')], default='NEWS', max_length=50),
        ),
    ]
