# Generated by Django 2.2.28 on 2023-09-18 13:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
