# Generated by Django 2.2.28 on 2023-09-25 16:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_pitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('rss_feed_url', models.URLField(blank=True, null=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_link_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name_attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('category_mapping', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON mapping of website categories to application categories', null=True)),
                ('article_link_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('article_link_attribute', models.CharField(blank=True, max_length=50, null=True)),
                ('article_link_prefix', models.URLField(blank=True, null=True)),
                ('article_link_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('date_published_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('date_published_format', models.CharField(blank=True, max_length=255, null=True)),
                ('article_title_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('article_content_selector', models.CharField(blank=True, max_length=255, null=True)),
                ('author_selector', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
