# Generated by Django 2.2.24 on 2023-09-28 20:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0007_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='access_count',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
