# Generated by Django 2.2.24 on 2023-10-02 21:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0008_newssource_access_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='scrape_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='access_count',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
