# Generated by Django 2.2.24 on 2023-10-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0009_auto_20231002_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='data_attribute_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='data_attribute_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
