# Generated by Django 2.2.24 on 2023-10-06 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0010_auto_20231005_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='error_log',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
