# Generated by Django 2.2.24 on 2023-10-06 23:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0011_newssource_error_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=150)),
                ('publish_date', models.DateTimeField()),
                ('link', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='comms.NewsSource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
