# Generated by Django 2.2.24 on 2023-10-09 17:25

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0012_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search_vector'], name='comms_artic_content_a6311c_gin'),
        ),
    ]
