# Generated by Django 2.2.28 on 2023-10-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0013_auto_20231009_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
