# Generated by Django 2.2.28 on 2023-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0014_newssource_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
