# Generated by Django 2.2.28 on 2023-10-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0015_auto_20231025_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
