# Generated by Django 2.2.28 on 2023-10-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0016_auto_20231025_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_styles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
