# Generated by Django 2.2.24 on 2023-11-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0017_writingstyle'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingstyle',
            name='title',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
