# Generated by Django 2.2.28 on 2023-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0019_emailalert'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('source', 'title'), name='unique_article'),
        ),
    ]
