# Generated by Django 2.2.28 on 2023-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0020_auto_20231114_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='article_link_regex',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
