# Generated by Django 2.2.28 on 2024-02-19 00:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0023_twitteraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalert',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
