# Generated by Django 2.2.28 on 2024-02-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0023_twitteraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitch',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
