# Generated by Django 2.2.28 on 2024-03-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0024_auto_20240229_0015'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date'], name='comms_artic_publish_f59c65_idx'),
        ),
    ]
