# Generated by Django 2.2.28 on 2024-04-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0026_auto_20240410_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
