# Generated by Django 2.2.28 on 2024-04-11 18:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0027_auto_20240411_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='facebook_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='hashtag_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
