# Generated by Django 2.2.28 on 2024-04-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0028_auto_20240411_1812'),
        ('comms', '0026_auto_20240408_1709'),
    ]

    operations = [
    ]
