# Generated by Django 2.2.28 on 2024-04-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0029_merge_20240416_0312'),
        ('comms', '0029_merge_20240415_2255'),
    ]

    operations = [
    ]
