# Generated by Django 2.2.28 on 2024-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0030_merge_20240416_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='description_selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='image_url_selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
