# Generated by Django 2.2.28 on 2024-05-10 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0031_auto_20240416_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('outlet', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
