# Generated by Django 2.2.28 on 2024-05-15 22:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0032_journalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='beats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='journalist',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalist',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
