# Generated by Django 2.2.28 on 2024-05-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0033_auto_20240515_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='coverage_type',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('LOCAL', 'Local'), ('BOTH', 'Both')], default='BOTH', max_length=50),
        ),
        migrations.AddField(
            model_name='journalist',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
