# Generated by Django 2.2.28 on 2024-05-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0034_auto_20240516_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
