# Generated by Django 2.2.28 on 2024-05-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0035_auto_20240517_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='is_crawling',
            field=models.BooleanField(default=False),
        ),
    ]
