# Generated by Django 2.2.28 on 2024-05-29 14:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0036_newssource_is_crawling'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('opens', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('recieved', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('activity_log', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
