# Generated by Django 2.2.28 on 2024-05-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0037_emailtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
