# Generated by Django 2.2.28 on 2024-06-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0038_emailtracker_clicks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtracker',
            old_name='recieved',
            new_name='received',
        ),
    ]
