# Generated by Django 2.2.28 on 2024-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0039_auto_20240604_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='accuracy_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journalist',
            name='number_of_sources',
            field=models.IntegerField(default=0),
        ),
    ]
