# Generated by Django 2.2.28 on 2024-06-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0040_auto_20240605_1356'),
        ('comms', '0024_emailalert_recipients'),
    ]

    operations = [
    ]
