# Generated by Django 2.2.28 on 2024-06-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0041_merge_20240619_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
