# Generated by Django 2.2.28 on 2024-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0042_emailtracker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NOT_WITH', 'No longer with outlet'), ('FREE', 'Freelancer'), ('CON', 'Contributor'), ('OPT', 'Opt out'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
