# Generated by Django 2.2.28 on 2024-06-26 16:58

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0043_journalist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalistContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None)),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comms.Journalist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='j_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
