# Generated by Django 2.2.28 on 2024-07-01 19:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0044_journalistcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalistcontact',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalistcontact',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AlterUniqueTogether(
            name='journalistcontact',
            unique_together={('user', 'journalist')},
        ),
    ]
