# Generated by Django 2.2.28 on 2024-07-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0045_auto_20240701_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalistcontact',
            options={'ordering': ['-datetime_created']},
        ),
    ]
