# Generated by Django 2.2.28 on 2024-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0047_companydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssource',
            name='rss_feed_url',
        ),
        migrations.AddField(
            model_name='newssource',
            name='scrape_type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('SITEMAP', 'Sitemap'), ('XML', 'XML')], default='HTML', max_length=50),
        ),
        migrations.AddField(
            model_name='newssource',
            name='sitemap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
