# Generated by Django 2.2.28 on 2024-08-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0048_auto_20240813_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalert',
            name='type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack')], default='EMAIL', max_length=50),
        ),
    ]
