# Generated by Django 2.2.28 on 2024-08-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0049_emailalert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalert',
            name='type',
            field=models.CharField(choices=[('NEWS', 'News'), ('SLACK', 'Slack'), ('BOTH', 'Both')], default='EMAIL', max_length=50),
        ),
    ]
