# Generated by Django 2.2.28 on 2024-08-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0050_auto_20240823_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalert',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailalert',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalistcontact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
