# Generated by Django 2.2.28 on 2024-08-23 16:53

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0051_auto_20240823_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NEWS', 'News'), ('SLACK', 'Slack'), ('BOTH', 'Both')], default='EMAIL', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('run_at', models.DateTimeField()),
                ('recipients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='comms.Search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={'verbose_name': 'Company Detail', 'verbose_name_plural': 'Company Details'},
        ),
        migrations.DeleteModel(
            name='EmailAlert',
        ),
    ]
