# Generated by Django 2.2.28 on 2024-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0052_auto_20240823_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistalert',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='assistalert',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
