# Generated by Django 2.2.28 on 2024-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0053_auto_20240823_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistalert',
            name='type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack'), ('BOTH', 'Both')], default='EMAIL', max_length=50),
        ),
    ]
