# Generated by Django 2.2.28 on 2024-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0055_discovery_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracker',
            name='bcc_recipients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtracker',
            name='cc_recipients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
