# Generated by Django 2.2.28 on 2024-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0056_auto_20240909_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='date_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
