# Generated by Django 2.2.28 on 2024-09-25 17:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0057_journalist_date_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalistcontact',
            name='notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), blank=True, default=list, null=True, size=None),
        ),
    ]
