# Generated by Django 2.2.28 on 2024-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0058_auto_20240925_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalist',
            name='review_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalistcontact',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='journalistcontact',
            name='outlet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
