# Generated by Django 2.2.28 on 2024-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0059_auto_20240925_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AddField(
            model_name='newssource',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
