# Generated by Django 2.2.28 on 2024-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0061_thread_threadmessage'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='threadmessage',
            constraint=models.UniqueConstraint(fields=('thread', 'index'), name='unique_message'),
        ),
    ]
