# Generated by Django 2.2.28 on 2024-11-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0062_auto_20241111_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadmessage',
            options={'ordering': ['index']},
        ),
    ]
