# Generated by Django 2.2.28 on 2024-11-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0063_auto_20241111_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='is_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newssource',
            name='posting_frequency',
            field=models.IntegerField(default=0),
        ),
    ]
