# Generated by Django 2.2.28 on 2024-12-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0064_auto_20241129_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='use_scrape_api',
            field=models.BooleanField(default=False),
        ),
    ]
