# Generated by Django 2.2.28 on 2024-12-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0065_newssource_use_scrape_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistalert',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='comms.Thread'),
        ),
        migrations.AlterField(
            model_name='assistalert',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='comms.Search'),
        ),
    ]
