# Generated by Django 2.2.28 on 2025-01-20 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_brin_index(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE INDEX article_publish_date_brin_idx
            ON comms_article USING brin (publish_date);
        """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("comms", "0066_auto_20241216_1351"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("archived_on", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(null=True)),
                ("author", models.CharField(blank=True, max_length=150, null=True)),
                ("publish_date", models.DateTimeField()),
                ("link", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=500)),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="comms_artic_content_a6311c_gin",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="comms_artic_publish_f59c65_idx",
        ),
        migrations.AddField(
            model_name="archivedarticle",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archived",
                to="comms.NewsSource",
            ),
        ),
        migrations.RunPython(create_brin_index),
    ]
