# Generated by Django 2.2.28 on 2025-01-27 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0067_auto_20250120_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date']},
        ),
    ]
