# Generated by Django 2.2.28 on 2025-02-10 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0068_auto_20250127_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='search',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to='comms.Search'),
        ),
        migrations.AlterField(
            model_name='search',
            name='type',
            field=models.CharField(choices=[('NEWS', 'News'), ('SOCIAL', 'Social Media'), ('OMNI', 'Omni'), ('WEB', 'Web'), ('TRENDING', 'Trending'), ('WRITE', 'Write'), ('DISCOVER', 'Discover')], default='NEWS', max_length=50),
        ),
    ]
