# Generated by Django 2.2.28 on 2025-02-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0069_auto_20250210_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistalert',
            name='search',
        ),
    ]
