# Generated by Django 2.2.28 on 2025-02-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0070_remove_assistalert_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to='comms.Search'),
        ),
    ]
