STAGE_TYPE_PRIVATE = "PRIVATE"
STAGE_TYPE_PUBLIC = "PUBLIC"

STAGE_TYPES = (
    (
        STAGE_TYPE_PRIVATE,
        "Private",
    ),
    (STAGE_TYPE_PUBLIC, "Public"),
)

INTEGRATION_SOURCE_SALESFORCE = "SALESFORCE"
INTEGRATION_SOURCES = ((INTEGRATION_SOURCE_SALESFORCE, "SalesForce"),)


ACCOUNT_TYPE_RENEWAL = "RENEWAL"
ACCOUNT_TYPE_NEW = "NEW"
ACCOUNT_TYPES = ((ACCOUNT_TYPE_RENEWAL, "Renewal"), (ACCOUNT_TYPE_NEW, "New"))
STATE_ACTIVE = "ACTIVE"
STATE_INACTIVE = "INACTIVE"
STATE_CHOCIES = ((STATE_ACTIVE, "Active"), (STATE_INACTIVE, "Inactive"))
