#/bin/bash
#
# Author: William Huster
# Date: January 16, 2021
# Description: Generates a single index.js so components can be conveniently
#              imported from the root of the components directory.
#
# NOTE: This "flattens" all of the components, so if you have two components
#       with the same name in different folders, you will have to correct that.
#
readarray -d '' array < <(find . -type f -name "*.vue" -print0)
# Clear index.js
header="/**
 * DO NOT EDIT: This is an autogenerated file.
 *
 * See gen_indexjs.sh in this directory.
 */
"
echo "${header}" > index.js
# Write each to index.js
for filepath in "${array[@]}"
do
  filename=$(basename -- "$filepath")
  echo "export { default as ${filename%%.*} } from '${filepath%.*}'" >> index.js
done