from django.conf import settings

SLACK_API_ROOT = "https://slack.com/api/"
SLACK_OAUTH_AUTHORIZE_ROOT = "https://slack.com/oauth/v2/authorize"

if settings.USE_SLACK:
    SLACK_SIGNING_SECRET = settings.SLACK_SIGNING_SECRET
    SLACK_APP_VERSION = settings.SLACK_APP_VERSION
    SLACK_ERROR_WEBHOOK = settings.SLACK_ERROR_WEBHOOK

if settings.IN_DEV:
    MANAGR_URL = "http://localhost:8080"
elif settings.IN_STAGING:
    MANAGR_URL = "https://staging.managr.ai"
else:
    MANAGR_URL = "https://app.managr.ai"

# https://api.slack.com/methods/oauth.v2.access
OAUTH_V2_ACCESS = "oauth.v2.access"

# https://api.slack.com/methods/conversations.open
CONVERSATIONS_OPEN = "conversations.open"

CONVERSATIONS_LIST = "conversations.list"
# https://api.slack.com/methods/chat.postMessage
POST_MESSAGE = "chat.postMessage"

POST_EPHEMERAL = "chat.postEphemeral"

# https://api.slack.com/methods/views.open

VIEWS_OPEN = "views.open"

VIEWS_UPDATE = "views.update"

VIEWS_PUSH = "views.push"

VIEWS_PUBLISH = "views.publish"

USERS_LIST = "users.list"

USERS_CONVERSATIONS = "users.conversations"

CONVERSATIONS_CREATE = "conversations.create"

CONVERSATIONS_INVITE = "conversations.invite"

CONVERSATIONS_INFO = "conversations.info"

# https://api.slack.com/methods/chat.getPermalink
CHAT_GET_PERMALINK = "chat.getPermalink"

# https://api.slack.com/methods/chat.update
CHAT_UPDATE = "chat.update"

WORKSPACE_SCOPES = [
    "chat:write",
    "commands",
    "channels:read",
    "groups:read",
    "im:write",
    "incoming-webhook",
    "channels:manage",
    "groups:write",
    "users:read",
    "users:read.email",
]

USER_SCOPES = ["channels:read"]

# Link Types to determine which type of OAuth link to generate
WORKSPACE = "WORKSPACE"
USER = "USER"
OAUTH_LINK_TYPES = [WORKSPACE, USER]

TOKEN_TYPE_BOT = "bot"

# Interactive payload types
BLOCK_ACTIONS = "block_actions"
BLOCK_SUGGESTION = "block_suggestion"
VIEW_SUBMISSION = "view_submission"
VIEW_CLOSED = "view_closed"

#
ZOOM_MEETING__PROCESS_MEETING_SENTIMENT = "ZOOM_MEETING__PROCESS_MEETING_SENTIMENT"

#########################################################
# BLOCK ACTION CONSTANTS
#########################################################
DEFAULT_ACTION_ID = "ACTION_ID"
ZOOM_MEETING__GREAT = "GREAT"
ZOOM_MEETING__FINE = "FINE"
ZOOM_MEETING__NOT_WELL = "NOT_WELL"
INSERT_NOTE_TEMPLATE_DROPDOWN = "INSERT_NOTE_TEMPLATE_DROPDOWN"
INSERT_NOTE_TEMPLATE = "INSERT_NOTE_TEMPLATE"

# MEETING BLOCK ACTIONS
SHOW_INITIAL_MEETING_INTERACTION = "SHOW_INITIAL_MEETING_INTERACTION"
ZOOM_MEETING__DIFFERENT_OPPORTUNITY = "ZOOM_MEETING__DIFFERENT_OPPORTUNITY"
GET_ORGANIZATION_STAGES = "GET_ORGANIZATION_STAGES"
GET_OPPORTUNITY_FORECASTS = "GET_OPPORTUNITY_FORECASTS"
GET_ORGANIZATION_ACTION_CHOICES = "GET_ORGANIZATION_ACTION_CHOICES"
GET_LOCAL_RESOURCE_OPTIONS = "GET_LOCAL_RESOURCE_OPTIONS"
GET_PRICEBOOK_ENTRY_OPTIONS = "GET_PRICEBOOK_ENTRY_OPTIONS"
GET_EXTERNAL_RELATIONSHIP_OPTIONS = "GET_EXTERNAL_RELATIONSHIP_OPTIONS"
GET_USER_OPPORTUNITIES = "GET_USER_OPPORTUNITIES"
ZOOM_MEETING__VIEW_MEETING_CONTACTS = "VIEW_MEETING_CONTACTS"
ZOOM_MEETING__EDIT_CONTACT = "EDIT_MEETING_CONTACT"
ZOOM_MEETING__UPDATE_PARTICIPANT_DATA = "UPDATE_MEETING_PARTICIPANT_DATA"
ZOOM_MEETING__UPDATE_CONTACT = "UPDATE_MEETING_CONTACT"
ZOOM_MEETING__SAVE_CONTACTS = "SAVE_MEETING_CONTACTS"
ZOOM_MEETING__CANCEL_EDIT_CONTACT = "CANCEL_EDIT_MEETING_CONTACT"
ZOOM_MEETING__REMOVE_CONTACT = "REMOVE_MEETING_CONTACT"
ZOOM_MEETING__UPDATE_FORECAST_SELECTION = "UPDATE_FORECAST_SELECTION"
ZOOM_MEETING__CREATE_OR_SEARCH = "CREATE_OR_SEARCH"
ZOOM_MEETING__DISREGARD_REVIEW = "DISREGARD_REVIEW"
ZOOM_MEETING__INIT_REVIEW = "INIT_MEETING_REVIEW"
ZOOM_MEETING__PROCESS_NO_CHANGES = "LOG_NO_CHANGES"
ZOOM_MEETING__CHANGE_RESOURCE = "CHANGE_RESOURCE"
ZOOM_MEETING__SELECTED_RESOURCE = "SELECTED_RESOURCE"
ZOOM_MEETING__SELECTED_CREATE_OR_SEARCH = "SELECTED_CREATE_OR_SEARCH"
ZOOM_MEETING__STAGE_SELECTED = "STAGE_SELECTED"
ZOOM_MEETING__PROCESS_STAGE_NEXT_PAGE = "ZOOM_MEETING_STAGE_NEXT_PAGE"
ZOOM_MEETING__PROCESS_NEXT_PAGE_CREATE = "ZOOM_MEETING_NEXT_PAGE_CREATE"
ZOOM_MEETING__SEARCH_OR_CREATE_NEXT_PAGE = "SEARCH_OR_CREATE_NEXT_PAGE"
ZOOM_MEETING__CONVERT_LEAD = "CONVERT_MEETING_LEAD"
ZOOM_MEETING__CREATE_TASK = "TASK_FROM_MEETING"
ZOOM_MEETING__LIST_TASKS = "ZOOM_MEETING__LIST_TASKS"
ZOOM_MEETING__SCHEDULE_MEETING = "ZOOM_MEETING__SCHEDULE_MEETING"
ZOOM_MEETING__ADD_CALENDAR_EVENT = "ZOOM_MEETING__ADD_CALENDAR_EVENT"
ZOOM_MEETING__MEETING_DETAILS = "ZOOM_MEETING__MEETING_DETAILS"
ZOOM_MEETING__GENERATIVE_ACTION = "ZOOM_MEETING__GENERATIVE_ACTION"
MEETING__PROCESS_SHOW_CHAT_MODEL = "MEETING__PROCESS_SHOW_CHAT_MODEL"
MEETING__PROCESS_TRANSCRIPT_TASK = "MEETING__PROCESS_TRANSCRIPT_TASK"
CALL_LAUNCH_SUMMARY_REVIEW = "CALL_LAUNCH_SUMMARY_REVIEW"
# COMMAND BLOCK ACTIONS
COMMAND_FORMS__STAGE_SELECTED = "COMMAND_FORMS__STAGE_SELECTED"
COMMAND_FORMS__SUBMIT_FORM = "COMMAND_FORMS__SUBMIT_FORM"
COMMAND_FORMS__PROCESS_NEXT_PAGE = "COMMAND_FORMS__PROCESS_NEXT_PAGE"
COMMAND_SUMMARY__GET_LOCAL_RESOURCE_OPTIONS = "COMMAND_SUMMARY__GET_LOCAL_RESOURCE_OPTIONS"
COMMAND_FORMS__GET_LOCAL_RESOURCE_OPTIONS = "COMMAND_FORMS__GET_LOCAL_RESOURCE_OPTIONS"
COMMAND_FORMS__CONVERT_LEAD = "COMMAND_FORMS__CONVERT_LEAD"
GET_EXTERNAL_PICKLIST_OPTIONS = "GET_EXTERNAL_PICKLIST_OPTIONS"
COMMAND_FORMS__PIPELINE_SELECTED = "COMMAND_FORMS__PIPELINE_SELECTED"
COMMAND_CREATE_TASK = "COMMAND_CREATE_TASK"
COMMAND_CREATE_EVENT = "COMMAND_CREATE_EVENT"
COMMAND_LIST_TASKS = "COMMAND_LIST_TASKS"
UPDATE_TASK_SELECTED_RESOURCE = "UPDATE_TASK_SELECTED_RESOURCE"
ZOOM_MEETING__SELECTED_RESOURCE_OPTION = "SELECTED_RESOURCE_OPTION"
RETURN_TO_FORM_MODAL = "RETURN_TO_FORM_MODAL"
CHECK_IS_OWNER_FOR_UPDATE_MODAL = "CHECK_IS_OWNER_FOR_UPDATE_MODAL"
COMMAND_LOG_NEW_ACTIVITY = "COMMAND_LOG_NEW_ACTIVITY"
GET_DEAL_STAGE_OPTIONS = "GET_DEAL_STAGE_OPTIONS"
GET_CRM_RESOURCE_OPTIONS = "GET_CRM_RESOURCE_OPTIONS"
RETURN_TO_FORM_BUTTON = "RETURN_TO_FORM_BUTTON"
PROCESS_INSERT_CHAT_TEMPLATE = "PROCESS_INSERT_CHAT_TEMPLATE"
PROCESS_INSERT_ACTION_TEMPLATE = "PROCESS_INSERT_ACTION_TEMPLATE"
# ALERT BLOCK ACTIONS
PROCESS_SHOW_ALERT_UPDATE_RESOURCE_FORM = "PROCESS_SHOW_ALERT_UPDATE_RESOURCE_FORM"
PAGINATE_ALERTS = "PAGINATE_ALERTS"
PAGINATE_MEETINGS = "PAGINATE_MEETINGS"
PAGINATE_TASKS = "PAGINATE_TASKS"
GET_USER_CONTACTS = "GET_USER_CONTACTS"
ADD_TO_CADENCE = "ADD_TO_CADENCE"
GET_CADENCE_OPTIONS = "GET_CADENCE_OPTIONS"
ADD_CONTACTS_TO_CADENCE = "ADD_CONTACTS_TO_CADENCE"
ADD_TO_SEQUENCE = "ADD_TO_SEQUENCE"
GET_SEQUENCE_OPTIONS = "GET_SEQUENCE_OPTIONS"
ADD_CONTACTS_TO_SEQUENCE = "ADD_CONTACTS_TO_SEQUENCE"
GET_CONTACT_OPTIONS = "GET_CONTACT_OPTIONS"
GET_USER_ACCOUNTS = "GET_USER_ACCOUNTS"
GET_SOBJECT_LIST = "GET_SOBJECT_LIST"
GONG_CALL_RECORDING = "GONG_CALL_RECORDING"
GET_NOTES = "GET_NOTES"
GONG_CALL_RECORDING = "GONG_CALL_RECORDING"
GET_CALLS = "GET_CALLS"
PROCESS_SEND_RECAP_MODAL = "PROCESS_SEND_RECAP_MODAL"
PROCESS_SEND_RECAPS = "PROCESS_SEND_RECAPS"
PROCESS_ADD_PRODUCTS_FORM = "PROCESS_ADD_PRODUCTS_FORM"
PROCESS_PICK_CUSTOM_OBJECT = "PROCESS_PICK_CUSTOM_OBJECT"
PROCESS_ADD_CUSTOM_OBJECT_FORM = "PROCESS_ADD_CUSTOM_OBJECT_FORM"
COMMAND_MANAGR_ACTION = "COMMAND_MANAGR_ACTION"
COMMAND_FORMS__SUBMIT_CHAT = "COMMAND_FORMS__SUBMIT_CHAT"
PROCESS_SHOW_EDIT_PRODUCT_FORM = "PROCESS_SHOW_EDIT_PRODUCT_FORM"
PROCESS_UPDATE_PRODUCT = "PROCESS_UPDATE_PRODUCT"
PROCESS_SUBMIT_PRODUCT = "PROCESS_SUBMIT_PRODUCT"
COMMAND_FORMS__PROCESS_ADD_CREATE_FORM = "COMMAND_FORMS__PROCESS_ADD_CREATE_FORM"
PROCESS_DIGEST_ATTACH_RESOURCE = "PROCESS_DIGEST_ATTACH_RESOURCE"
VIEW_RECAP = "VIEW_RECAP"
PROCESS_LEAD_INPUT_SWITCH = "PROCESS_LEAD_INPUT_SWITCH"
PROCESS_SELECT_RESOURCE = "PROCESS_SELECT_RESOURCE"
PROCESS_SHOW_ENGAGEMENT_MODEL = "PROCESS_SHOW_ENGAGEMENT_MODEL"
PROCESS_ALERT_ACTIONS = "PROCESS_ALERT_ACTIONS"
PROCESS_BULK_UPDATE = "PROCESS_BULK_UPDATE"
CHOOSE_CRM_FIELD = "CHOOSE_CRM_FIELD"
GET_SUMMARY = "GET_SUMMARY"
CHOOSE_CRM_FIELDS = "CHOOSE_CRM_FIELDS"
PROCESS_SWITCH_ALERT_MESSAGE = "PROCESS_SWITCH_ALERT_MESSAGE"
PROCESS_INLINE_FIELD_SELECTED = "PROCESS_INLINE_FIELD_SELECTED"
PAGINATE_INLINE_ALERTS = "PAGINATE_INLINE_ALERTS"
PROCESS_SUBMIT_INLINE_ALERT_DATA = "PROCESS_SUBMIT_INLINE_ALERT_DATA"
ALERT_INLINE_STAGE_SELECTED = "ALERT_INLINE_STAGE_SELECTED"
ALERT_INLINE_STAGE_SUBMITTED = "ALERT_INLINE_STAGE_SUBMITTED"
MEETING_REVIEW_SYNC_CALENDAR = "MEETING_REVIEW_SYNC_CALENDAR"
MEETING_ATTACH_RESOURCE_MODAL = "MEETING_ATTACH_RESOURCE_MODAL"
PROCESS_SHOW_APP_SELECT = "PROCESS_SHOW_APP_SELECT"
PAGINATE_NOTE_ALERTS = "PAGINATE_NOTE_ALERTS"
PAGINATE_APP_ALERTS = "PAGINATE_APP_ALERTS"
PROCESS_SHOW_ENGAGEMENT_DETAILS = "PROCESS_SHOW_ENGAGEMENT_DETAILS"
REOPEN_CHAT_MODAL = "REOPEN_CHAT_MODAL"
OPEN_GENERATIVE_ACTION_MODAL = "OPEN_GENERATIVE_ACTION_MODAL"
PROCESS_SELECT_GENERATIVE_ACTION = "PROCESS_SELECT_GENERATIVE_ACTION"
PROCESS_REGENERATE_ACTION = "PROCESS_REGENERATE_ACTION"
PROCESS_SWITCH_TO_DEAL_REVIEW = "PROCESS_SWITCH_TO_DEAL_REVIEW"
PROCESS_SEND_DEAL_REVIEW = "PROCESS_SEND_DEAL_REVIEW"
PROCESS_PAGINATE_DEAL_REVIEW = "PROCESS_PAGINATE_DEAL_REVIEW"
OPEN_REVIEW_CHAT_UPDATE_MODAL = "OPEN_REVIEW_CHAT_UPDATE_MODAL"
#########################################################
# VIEW SUBMISSION CONSTANTS
#########################################################
PROCESS_SUBMIT_ALERT_RESOURCE_DATA = "PROCESS_SUBMIT_ALERT_RESOURCE_DATA"
PROCESS_SUBMIT_BULK_UPDATE = "PROCESS_SUBMIT_BULK_UPDATE"
SUBMIT_CUSTOM_OBJECT_DATA = "SUBMIT_CUSTOM_OBJECT_DATA"
GET_PICKLIST_OPTIONS = "GET_PICKLIST_OPTIONS"
PROCESS_SELECTED_GENERATIVE_ACTION = "PROCESS_SELECTED_GENERATIVE_ACTION"
MEETING___SUBMIT_CHAT_PROMPT = "MEETING___SUBMIT_CHAT_PROMPT"
MEETING__SHOW_TRANSCRIPT_MESSAGE = "MEETING__SHOW_TRANSCRIPT_MESSAGE"
MEETING__UPDATE_TRANSCRIPT_MESSAGE = "MEETING__UPDATE_TRANSCRIPT_MESSAGE"
MEETING__SUBMIT_USE_TRANSCRIPT = "MEETING__SUBMIT_USE_TRANSCRIPT"
PROCESS_CHAT_ACTION = "PROCESS_CHAT_ACTION"
# Static Block ID's
ZOOM_MEETING__ATTACH_RESOURCE_SECTION = "ATTACH_RESOURCE_SECTION"

OPPORTUNITY_CREATE_FORM = "Opportunity.CREATE"
OPPORTUNITY_UPDATE_FORM = "Opportunity.UPDATE"
OPPORTUNITY_MEETING_REVIEW_FORM = "Opportunity.MEETING_REVIEW"
ACCOUNT_CREATE_FORM = "Account.CREATE"
ACCOUNT_UPDATE_FORM = "Account.UPDATE"
ACCOUNT_MEETING_REVIEW_FORM = "Account.MEETING_REVIEW"
CONTACT_CREATE_FORM = "Contact.CREATE"
CONTACT_UPDATE_FORM = "Contact.UPDATE"
LEAD_MEETING_REVIEW_FORM = "Lead.MEETING_REVIEW"
LEAD_CREATE_FORM = "Lead.CREATE"
LEAD_UPDATE_FORM = "Lead.UPDATE"
OPPORTUNITYLINEITEM_CREATE_FORM = "OpportunityLineItem.CREATE"
OPPORTUNITYLINEITEM_UPDATE_FORM = "OpportunityLineItem.UPDATE"
DEAL_CREATE_FORM = "Deal.CREATE"
DEAL_UPDATE_FORM = "Deal.UPDATE"
COMPANY_CREATE_FORM = "Company.CREATE"
COMPANY_UPDATE_FORM = "Company.UPDATE"

SLACK_ACTION_RESOURCE_ACTION_CHOICE = "ActionChoice"
SLACK_ACTION_RESOURCE_PRICEBOOKENTRY = "PricebookEntry"

FORM_RESOURCE_OPPORTUNITY = "Opportunity"
FORM_RESOURCE_ACCOUNT = "Account"
FORM_RESOURCE_CONTACT = "Contact"
FORM_RESOURCE_LEAD = "Lead"
FORM_RESOURCE_DEAL = "Deal"
FORM_RESOURCE_COMPANY = "Company"
FORM_RESOURCE_OPPORTUNITYLINEITEM = "OpportunityLineItem"

SALESFORCE_FORM_RESOURCES = [
    FORM_RESOURCE_ACCOUNT,
    FORM_RESOURCE_OPPORTUNITY,
    FORM_RESOURCE_CONTACT,
    FORM_RESOURCE_LEAD,
    FORM_RESOURCE_OPPORTUNITYLINEITEM,
]

FORM_RESOURCE_DEAL = "Deal"
FORM_RESOURCE_COMPANY = "Company"
FORM_RESOURCE_HUBSPOTCONTACT = "Contact"
FORM_RESOURCE_CUSTOMOBJECT = "CustomObject"

FORM_RESOURCES = (
    (
        "Salesforce",
        (
            (FORM_RESOURCE_OPPORTUNITY, "Opportunity"),
            (FORM_RESOURCE_ACCOUNT, "Account"),
            (FORM_RESOURCE_CONTACT, "Contact"),
            (FORM_RESOURCE_LEAD, "Lead"),
            (FORM_RESOURCE_OPPORTUNITYLINEITEM, "OpportunityLineItem"),
            (FORM_RESOURCE_CUSTOMOBJECT, "CustomObject"),
        ),
    ),
    (
        "Hubspot",
        (
            (FORM_RESOURCE_DEAL, "Deal"),
            (FORM_RESOURCE_COMPANY, "Company"),
            (FORM_RESOURCE_HUBSPOTCONTACT, "Contact"),
            (FORM_RESOURCE_CUSTOMOBJECT, "CustomObject"),
        ),
    ),
)


FORM_TYPE_CREATE = "CREATE"
FORM_TYPE_UPDATE = "UPDATE"
FORM_TYPE_MEETING_REVIEW = "MEETING_REVIEW"
FORM_TYPE_STAGE_GATING = "STAGE_GATING"

# When attaching a resource to a meeting use these options
MEETING_RESOURCE_ATTACHMENT_OPTIONS = (
    FORM_RESOURCE_ACCOUNT,
    FORM_RESOURCE_OPPORTUNITY,
    FORM_RESOURCE_LEAD,
    FORM_RESOURCE_CONTACT,
)

MEETING_RESOURCE_HUBSPOT_ATTACHMENT_OPTIONS = (
    FORM_RESOURCE_COMPANY,
    FORM_RESOURCE_DEAL,
    FORM_RESOURCE_CONTACT,
)


INITIAL_FORMS = [
    CONTACT_CREATE_FORM,
    CONTACT_UPDATE_FORM,
    OPPORTUNITY_CREATE_FORM,
    OPPORTUNITY_UPDATE_FORM,
    ACCOUNT_CREATE_FORM,
    ACCOUNT_UPDATE_FORM,
    LEAD_CREATE_FORM,
    LEAD_UPDATE_FORM,
    OPPORTUNITYLINEITEM_CREATE_FORM,
    OPPORTUNITYLINEITEM_UPDATE_FORM,
]

INITIAL_HUBSPOT_FORMS = [
    DEAL_CREATE_FORM,
    DEAL_UPDATE_FORM,
    COMPANY_CREATE_FORM,
    COMPANY_UPDATE_FORM,
    CONTACT_CREATE_FORM,
    CONTACT_UPDATE_FORM,
]

FORM_TYPES = (
    (FORM_TYPE_CREATE, "Create"),
    (FORM_TYPE_UPDATE, "Update"),
    (FORM_TYPE_STAGE_GATING, "Stage Gating"),
)

SLACK_ACTION_RESOURCE_USER = "User"

FORM_TYPES_LIST = [
    FORM_TYPE_CREATE,
    FORM_TYPE_UPDATE,
    FORM_TYPE_STAGE_GATING,
]

FORM_RESOURCE_LIST = [
    FORM_RESOURCE_OPPORTUNITY,
    FORM_RESOURCE_ACCOUNT,
    FORM_RESOURCE_CONTACT,
    FORM_RESOURCE_LEAD,
    FORM_RESOURCE_OPPORTUNITYLINEITEM,
]

UPDATE_PUBLIC_FIELD_IDS = [
    "6407b7a1-a877-44e2-979d-1effafec5034",
    "0bb152b5-aac1-4ee0-9c25-51ae98d55af2",
]
CREATE_PUBLIC_FIELD_IDS = [*UPDATE_PUBLIC_FIELD_IDS]
MEETING_REVIEW_PUBLIC_FIELD_IDS = [*UPDATE_PUBLIC_FIELD_IDS]


DEFAULT_PUBLIC_FORM_FIELDS = {
    FORM_RESOURCE_ACCOUNT: {
        FORM_TYPE_CREATE: [*CREATE_PUBLIC_FIELD_IDS],
        FORM_TYPE_UPDATE: [*UPDATE_PUBLIC_FIELD_IDS],
    },
    FORM_RESOURCE_CONTACT: {
        FORM_TYPE_CREATE: [*CREATE_PUBLIC_FIELD_IDS],
        FORM_TYPE_UPDATE: [*UPDATE_PUBLIC_FIELD_IDS],
    },
    FORM_RESOURCE_LEAD: {
        FORM_TYPE_CREATE: [*CREATE_PUBLIC_FIELD_IDS],
        FORM_TYPE_UPDATE: [*UPDATE_PUBLIC_FIELD_IDS],
    },
    FORM_RESOURCE_OPPORTUNITY: {
        FORM_TYPE_CREATE: [*CREATE_PUBLIC_FIELD_IDS],
        FORM_TYPE_UPDATE: [*UPDATE_PUBLIC_FIELD_IDS],
    },
    FORM_RESOURCE_COMPANY: {
        FORM_TYPE_CREATE: [*CREATE_PUBLIC_FIELD_IDS],
        FORM_TYPE_UPDATE: [*UPDATE_PUBLIC_FIELD_IDS],
    },
    FORM_RESOURCE_DEAL: {
        FORM_TYPE_CREATE: [*CREATE_PUBLIC_FIELD_IDS],
        FORM_TYPE_UPDATE: [*UPDATE_PUBLIC_FIELD_IDS],
    },
}


NO_FORM_FIELDS = "NO_FORM_FIELDS"

MANAGR_ACTIONS = [
    ("CREATE_RESOURCE", "Create New Record"),
    ("GET_NOTES", "View Notes"),
    ("SCHEDULE_MEETING", "Schedule Zoom Meeting"),
]

SALESFORCE_ACTIONS = [
    ("CONVERT_LEAD", "Convert Lead"),
    ("LOG_NEW_ACTIVITY", "Log New Activity"),
    ("LIST_TASKS", "List Tasks"),
]

