import SlackAPI from './api'

export default class SlackOAuth {
  static api = SlackAPI.create(SlackOAuth)
  static options = {
    WORKSPACE: 'WORKSPACE',
    USER: 'USER',
  }
  static redirectURI =
    window.location.protocol + '//' + window.location.host + '/settings/integrations'
}

// The following data structure would usually be retrieved from Salesforce
// to represent the fields available to the user
export const salesforceFields = {
  Opportunity: {
    fields: {
      Id: {
        key: 'Id',
        type: 'String',
        label: 'Opportunity ID',
        options: [],
        required: true,
        updateable: false,
      },
      Name: {
        key: 'Name',
        type: 'String',
        label: 'Name',
        options: [],
        required: true,
        updateable: true,
      },
      Type: {
        key: 'Type',
        type: 'Picklist',
        label: 'Opportunity Type',
        options: [],
        required: false,
        updateable: true,
      },
      IsWon: {
        key: 'IsWon',
        type: 'Boolean',
        label: 'Won',
        options: [],
        required: true,
        updateable: false,
      },
      Amount: {
        key: 'Amount',
        type: 'Currency',
        label: 'Amount',
        options: [],
        required: false,
        updateable: true,
      },
      Fiscal: {
        key: 'Fiscal',
        type: 'String',
        label: 'Fiscal Period',
        options: [],
        required: false,
        updateable: false,
      },
      OwnerId: {
        key: 'OwnerId',
        type: 'Reference',
        label: 'Owner ID',
        options: [],
        required: true,
        updateable: true,
      },
      IsClosed: {
        key: 'IsClosed',
        type: 'Boolean',
        label: 'Closed',
        options: [],
        required: true,
        updateable: false,
      },
      NextStep: {
        key: 'NextStep',
        type: 'String',
        label: 'Next Step',
        options: [],
        required: false,
        updateable: true,
      },
      AccountId: {
        key: 'AccountId',
        type: 'Reference',
        label: 'Account ID',
        options: [],
        required: false,
        updateable: true,
      },
      CloseDate: {
        key: 'CloseDate',
        type: 'Date',
        label: 'Close Date',
        options: [],
        required: true,
        updateable: true,
      },
      ContactId: {
        key: 'ContactId',
        type: 'Reference',
        label: 'Contact ID',
        options: [],
        required: false,
        updateable: false,
      },
      IsDeleted: {
        key: 'IsDeleted',
        type: 'Boolean',
        label: 'Deleted',
        options: [],
        required: true,
        updateable: false,
      },
      IsPrivate: {
        key: 'IsPrivate',
        type: 'Boolean',
        label: 'Private',
        options: [],
        required: true,
        updateable: true,
      },
      StageName: {
        key: 'StageName',
        type: 'Picklist',
        label: 'Stage',
        options: [],
        required: true,
        updateable: true,
      },
      CampaignId: {
        key: 'CampaignId',
        type: 'Reference',
        label: 'Campaign ID',
        options: [],
        required: false,
        updateable: true,
      },
      FiscalYear: {
        key: 'FiscalYear',
        type: 'Int',
        label: 'Fiscal Year',
        options: [],
        required: false,
        updateable: false,
      },
      LeadSource: {
        key: 'LeadSource',
        type: 'Picklist',
        label: 'Lead Source',
        options: [],
        required: false,
        updateable: true,
      },
      CreatedById: {
        key: 'CreatedById',
        type: 'Reference',
        label: 'Created By ID',
        options: [],
        required: true,
        updateable: false,
      },
      CreatedDate: {
        key: 'CreatedDate',
        type: 'DateTime',
        label: 'Created Date',
        options: [],
        required: true,
        updateable: false,
      },
      Description: {
        key: 'Description',
        type: 'TextArea',
        label: 'Description',
        options: [],
        required: false,
        updateable: true,
      },
      Probability: {
        key: 'Probability',
        type: 'Percent',
        label: 'Probability (%)',
        options: [],
        required: false,
        updateable: true,
      },
      Heroku_id__c: {
        key: 'Heroku_id__c',
        type: 'String',
        label: 'Managr Id',
        options: [],
        required: false,
        updateable: true,
      },
      Pricebook2Id: {
        key: 'Pricebook2Id',
        type: 'Reference',
        label: 'Price Book ID',
        options: [],
        required: false,
        updateable: true,
      },
      CloneSourceId: {
        key: 'CloneSourceId',
        type: 'Reference',
        label: 'Clone Source',
        options: [],
        required: false,
        updateable: false,
      },
      FiscalQuarter: {
        key: 'FiscalQuarter',
        type: 'Int',
        label: 'Fiscal Quarter',
        options: [],
        required: false,
        updateable: false,
      },
      HasOverdueTask: {
        key: 'HasOverdueTask',
        type: 'Boolean',
        label: 'Has Overdue Task',
        options: [],
        required: true,
        updateable: false,
      },
      LastViewedDate: {
        key: 'LastViewedDate',
        type: 'DateTime',
        label: 'Last Viewed Date',
        options: [],
        required: false,
        updateable: false,
      },
      OrderNumber__c: {
        key: 'OrderNumber__c',
        type: 'String',
        label: 'Order Number',
        options: [],
        required: false,
        updateable: true,
      },
      SystemModstamp: {
        key: 'SystemModstamp',
        type: 'DateTime',
        label: 'System Modstamp',
        options: [],
        required: true,
        updateable: false,
      },
      ExpectedRevenue: {
        key: 'ExpectedRevenue',
        type: 'Currency',
        label: 'Expected Amount',
        options: [],
        required: false,
        updateable: false,
      },
      HasOpenActivity: {
        key: 'HasOpenActivity',
        type: 'Boolean',
        label: 'Has Open Activity',
        options: [],
        required: true,
        updateable: false,
      },
      ForecastCategory: {
        key: 'ForecastCategory',
        type: 'Picklist',
        label: 'Forecast Category',
        options: [],
        required: true,
        updateable: false,
      },
      LastActivityDate: {
        key: 'LastActivityDate',
        type: 'Date',
        label: 'Last Activity',
        options: [],
        required: false,
        updateable: false,
      },
      LastModifiedById: {
        key: 'LastModifiedById',
        type: 'Reference',
        label: 'Last Modified By ID',
        options: [],
        required: true,
        updateable: false,
      },
      LastModifiedDate: {
        key: 'LastModifiedDate',
        type: 'DateTime',
        label: 'Last Modified Date',
        options: [],
        required: true,
        updateable: false,
      },
      Managr_Amount__c: {
        key: 'Managr_Amount__c',
        type: 'Currency',
        label: 'Managr Amount',
        options: [],
        required: false,
        updateable: true,
      },
      TrackingNumber__c: {
        key: 'TrackingNumber__c',
        type: 'String',
        label: 'Tracking Number',
        options: [],
        required: false,
        updateable: true,
      },
      LastReferencedDate: {
        key: 'LastReferencedDate',
        type: 'DateTime',
        label: 'Last Referenced Date',
        options: [],
        required: false,
        updateable: false,
      },
      MainCompetitors__c: {
        key: 'MainCompetitors__c',
        type: 'String',
        label: 'Main Competitor(s)',
        options: [],
        required: false,
        updateable: true,
      },
      CurrentGenerators__c: {
        key: 'CurrentGenerators__c',
        type: 'String',
        label: 'Current Generator(s)',
        options: [],
        required: false,
        updateable: true,
      },
      ForecastCategoryName: {
        key: 'ForecastCategoryName',
        type: 'Picklist',
        label: 'Forecast Category',
        options: [],
        required: false,
        updateable: true,
      },
      Heroku_id_formula__c: {
        key: 'Heroku_id_formula__c',
        type: 'String',
        label: 'Managr Id',
        options: [],
        required: false,
        updateable: false,
      },
      HasOpportunityLineItem: {
        key: 'HasOpportunityLineItem',
        type: 'Boolean',
        label: 'Has Line Item',
        options: [],
        required: true,
        updateable: false,
      },
      TotalOpportunityQuantity: {
        key: 'TotalOpportunityQuantity',
        type: 'Double',
        label: 'Quantity',
        options: [],
        required: false,
        updateable: true,
      },
      LastAmountChangedHistoryId: {
        key: 'LastAmountChangedHistoryId',
        type: 'Reference',
        label: 'Opportunity History ID',
        options: [],
        required: false,
        updateable: false,
      },
      Managr_Account_Id_Formula__c: {
        key: 'Managr_Account_Id_Formula__c',
        type: 'String',
        label: 'Managr_Account_Id',
        options: [],
        required: false,
        updateable: false,
      },
      DeliveryInstallationStatus__c: {
        key: 'DeliveryInstallationStatus__c',
        type: 'Picklist',
        label: 'Delivery/Installation Status',
        options: [],
        required: false,
        updateable: true,
      },
      LastCloseDateChangedHistoryId: {
        key: 'LastCloseDateChangedHistoryId',
        type: 'Reference',
        label: 'Opportunity History ID',
        options: [],
        required: false,
        updateable: false,
      },
    },
    validations: [
      { id: '03d5g000000PMH9AAO', message: 'Add A desc', description: 'Required description' },
    ],
    record_type_id: '012000000000000AAA',
  },
}
