from django.conf import settings

from managr.utils.misc import get_site_url

USE_NYLAS = settings.USE_NYLAS
NYLAS_CLIENT_ID = settings.NYLAS_CLIENT_ID if USE_NYLAS else None
NYLAS_CLIENT_SECRET = settings.NYLAS_CLIENT_SECRET if USE_NYLAS else None
NYLAS_OAUTH_CALLBACK_URL = settings.NYLAS_OAUTH_CALLBACK_URL if USE_NYLAS else None
NYLAS_API_BASE_URL = "https://api.nylas.com"
EMAIL_AUTH_URI = "oauth/authorize"
EMAIL_AUTH_TOKEN_URI = "oauth/token"
EMAIL_AUTH_TOKEN_REVOKE_URI = "oauth/revoke"
EMAIL_ACCOUNT_URI = "account"
SEND_EMAIL_URI = "send"


USE_TWILIO = settings.USE_TWILIO
ACCOUNT_SID = settings.TWILIO_ACCOUNT_SID if USE_TWILIO else None
AUTH_TOKEN = settings.TWILIO_AUTH_TOKEN if USE_TWILIO else None
TWILIO_MESSAGE_STATUS_CALLBACK_URL = (
    f"{settings.TWILIO_BASE_CALLBACK_URL}/api/twilio/callback/messages/status"
    if USE_TWILIO
    else None
)
TWILIO_MESSAGE_RECEIVED_CALLBACK_URL = (
    f"{settings.TWILIO_BASE_CALLBACK_URL}/api/twilio/callback/messages"
    if USE_TWILIO
    else None
)


# OAuth permission scopes to request from Nylas
SCOPE_EMAIL_READ_ONLY = "email.read_only"
SCOPE_EMAIL_SEND = "email.send"
ALL_SCOPES = [
    SCOPE_EMAIL_READ_ONLY,
    SCOPE_EMAIL_SEND,
]
ALL_SCOPES_STR = ", ".join(ALL_SCOPES)

NYLAS_WEBHOOK_TYPE_MSG_CREATED = "message.created"
NYLAS_WEBHOOK_TYPE_MSG_OPENED = "message.opened"
NYLAS_WEBHOOK_OBJECT_MESSAGE = "message"
NYLAS_WEBHOOK_OBJECT_METADATA = "metadata"
NYLAS_WEBHOOK_TYPES = (
    (
        NYLAS_WEBHOOK_TYPE_MSG_CREATED,
        "Message Created",
    ),
    (
        NYLAS_WEBHOOK_TYPE_MSG_OPENED,
        "Message Opened",
    ),
)
NYLAS_WEBHOOK_OBJECTS = (
    (NYLAS_WEBHOOK_OBJECT_MESSAGE, "message"),
    (NYLAS_WEBHOOK_OBJECT_METADATA, "metadata"),
)


def EMAIL_REVOKE_ALL_TOKENS_URI(account_id):
    return f"a/{NYLAS_CLIENT_ID}/accounts/{account_id}/revoke-all/"


ACCOUNT_TYPE_LIMITED = "LIMITED"
ACCOUNT_TYPE_MANAGER = "MANAGER"
ACCOUNT_TYPE_REP = "REP"
ACCOUNT_TYPE_ADMIN = "ADMIN"  # these are org level admins
ACCOUNT_TYPE_INTEGRATION = "INTEGRATION"  # these are for external integrations
ACCOUNT_TYPES = (
    (ACCOUNT_TYPE_LIMITED, "LIMITED"),
    (ACCOUNT_TYPE_MANAGER, "MANAGER"),
    (ACCOUNT_TYPE_INTEGRATION, "INTEGRATION"),
    (ACCOUNT_TYPE_REP, "REP"),
    (ACCOUNT_TYPE_ADMIN, "ADMIN"),
)

STATE_ACTIVE = "ACTIVE"
STATE_INACTIVE = "INACTIVE"
STATE_INVITED = "INVITED"
STATE_CHOCIES = (
    (STATE_ACTIVE, "Active"),
    (STATE_INACTIVE, "Inactive"),
    (STATE_INVITED, "Invited"),
)

SERVICE_TYPE_NULL = None
SERVICE_TYPE_EMAIL = "EMAIL"
SERVICE_TYPE_EXTERNAL_API = "EXTERNAL"
SERVICE_TYPES = (
    (SERVICE_TYPE_EMAIL, "Email"),
    (SERVICE_TYPE_EXTERNAL_API, "External"),
    (SERVICE_TYPE_NULL, None),
)

NYLAS_SYNC_STATUS_STOPPED = "stopped"
NYLAS_SYNC_STATUS_INVALID = "invalid"
NYLAS_SYNC_STATUS_SYNC_ERROR = "sync_error"
NYLAS_SYNC_STATUSES_FAILING = (
    NYLAS_SYNC_STATUS_STOPPED,
    NYLAS_SYNC_STATUS_INVALID,
    NYLAS_SYNC_STATUS_SYNC_ERROR,
)

NOTIFICATION_TYPE_ALERT = "ALERT"
NOTIFICATION_TYPE_EMAIL = "EMAIL"
NOTIFICATION_TYPES = (
    (
        NOTIFICATION_TYPE_ALERT,
        "ALERT",
    ),
    (
        NOTIFICATION_TYPE_EMAIL,
        "EMAIL",
    ),
)


NOTIFICATION_RESOURCE_ACCOUNT = "ACCOUNT"
NOTIFICATION_RESOURCE_ORGANIZATION = "ORGANIZATION"

NOTIFICATION_RESOURCE_REPORT = "REPORT"
NOTIFICATION_RESOURCE_OPPORTUNITY = "OPPORTUNITY"
NOTIFICATION_RESOURCE_USER = "USER"
NOTIFICATION_RESOURCES = (
    (
        NOTIFICATION_RESOURCE_ACCOUNT,
        "Account",
    ),
    (NOTIFICATION_RESOURCE_ORGANIZATION, "Organization"),
    (NOTIFICATION_RESOURCE_REPORT, "Report"),
    (NOTIFICATION_RESOURCE_OPPORTUNITY, "Opportunity"),
)

NOTIFICATION_OPTION_KEY_OPPORTUNITY_EMAIL_RECEIVED = "OPPORTUNITY_EMAIL_RECEIVED"
NOTIFICATION_OPTION_KEY_ORGANIZATION_STAGES = "ORGANIZATION_STAGES_UPDATE"
NOTIFICATION_OPTION_KEY_REPORT_GENERATED = "REPORT_GENERATED"
NOTIFICATION_OPTION_KEY_USER_UPDATE = "USER_UPDATE"
NOTIFICATION_OPTION_KEY_OPPORTUNITY_TEXT_RECEIVED = "OPPORTUNITY_TEXT_RECEIVED"
NOTIFICATION_OPTION_KEY_OPPORTUNITY_REMINDER = "OPPORTUNITY_REMINDER"
NOTIFICATION_OPTION_KEY_OPPORTUNITY_STALLED_IN_STAGE = "OPPORTUNITY_STALLED_IN_STAGE"
NOTIFICATION_OPTION_KEY_OPPORTUNITY_INACTIVE_90_DAYS = "OPPORTUNITY_INACTIVE_90_DAYS"
NOTIFICATION_OPTION_KEY_OPPORTUNITY_LAPSED_EXPECTED_CLOSE_DATE_1_DAY = (
    "OPPORTUNITY_LAPSED_CLOSE_DATE_1_DAY"
)
NOTIFICATION_OPTION_KEY_OPPORTUNITY_LAPSED_EXPECTED_CLOSE_DATE_14_DAYS = (
    "OPPORTUNITY_LAPSED_CLOSE_DATE_14_DAYS"
)
NOTIFICATION_OPTION_KEY_OPPORTUNITY_LAPSED_EXPECTED_CLOSE_DATE_30_DAYS = (
    "OPPORTUNITY_LAPSED_CLOSE_DATE_30_DAYS"
)
NOTIFICATION_OPTION_KEY_OPPORTUNITY_EMAIL_RECEIVED_ID = (
    "004c41a0-11c2-4b33-bcec-4e10518d2fa3"
)


#### constants for testing grabbing id's from fixtures
NOTIFICATION_OPTION_STALLED_IN_STAGE_ID = "f9cc3934-f82b-442f-9d63-73de73d5d115"
NOTIFICATION_OPTION_INACTIVE_ID = "845c1d76-8743-4695-b6cf-9af7b0aaab14"
NOTIFICATION_OPTION_LAPSED_1_DAY_ID = "5d19b999-c0bf-429a-a8f5-17b9bc2efdc6"
NOTIFICATION_OPTION_LAPSED_14_DAYS_ID = "2bcddc82-305b-42a8-a295-99b76f418aac"
NOTIFICATION_OPTION_LAPSED_30_DAYS_ID = "0285c84d-10c5-41d8-8a97-d944cc373ad6"
NOTIFICATION_OPTION_STAGE_UPDATE_ID = "0e0a1e9d-f806-4807-8d09-58e90346edff"
