# Generated by Django 2.2.24 on 2021-11-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachaccount',
            name='mailbox',
            field=models.IntegerField(null=True),
        ),
    ]
