# Generated by Django 2.2.24 on 2021-11-19 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_organization_ignore_emails'),
        ('outreach', '0002_outreachaccount_mailbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='contact_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect', to='organization.Contact'),
        ),
    ]
