# Generated by Django 2.2.24 on 2021-11-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0003_prospect_contact_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='prospects_id',
            new_name='prospect_id',
        ),
    ]
