# Generated by Django 2.2.24 on 2023-02-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outreach', '0004_auto_20211119_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachaccount',
            name='instance_url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
